function summary = plot_trust_rollback_anchor_main_figure(varargin)
%PLOT_TRUST_ROLLBACK_ANCHOR_MAIN_FIGURE Compact proof-of-concept figure.
%
% The expected file order is:
%   1. no rollback
%   2. rollback
%   3. rollback + anchoring
%
% Common usage:
%   plot_trust_rollback_anchor_main_figure
%   plot_trust_rollback_anchor_main_figure('Focus', 2)
%   plot_trust_rollback_anchor_main_figure('Files', files, 'Focus', 2)
%   plot_trust_rollback_anchor_main_figure('Files', files, 'Focus', 2, 'Attacker', 1)
%   plot_trust_rollback_anchor_main_figure('Save', true, 'OutputDir', 'paper_figures')
%   plot_trust_rollback_anchor_main_figure('TimeMode', 'relative', 'TimeWindow', [-2 10])
%   plot_trust_rollback_anchor_main_figure('PlotTrajectory', true)
%
% The figure contains:
%   (a) final position-estimation error for the three cases
%   (b) attacker/source rejection signal, preferably source weight
%   (c) generalized/final trust drop for the attacked source
%   (d) rollback correction: before/after rollback curves
%
% A second XY trajectory figure is also generated by default. It compares
% the reference and final estimated trajectory for the three cases.

parser = inputParser;
addParameter(parser, 'Files', strings(0, 1), @(x) isstring(x) || iscell(x) || ischar(x));
addParameter(parser, 'CaseNames', strings(0, 1), @(x) isstring(x) || iscell(x) || ischar(x));
addParameter(parser, 'Focus', 0, @(x) isscalar(x) && isnumeric(x));
addParameter(parser, 'Attacker', NaN, @(x) isscalar(x) && isnumeric(x));
addParameter(parser, 'Host', 1, @(x) isscalar(x) && isnumeric(x));
addParameter(parser, 'ResultDate', '', @(x) ischar(x) || isstring(x));
addParameter(parser, 'SelectFiles', true, @(x) islogical(x) || isnumeric(x));
addParameter(parser, 'Save', true, @(x) islogical(x) || isnumeric(x));
addParameter(parser, 'OutputDir', 'paper_figures', @(x) ischar(x) || isstring(x));
addParameter(parser, 'Formats', ["png", "pdf"], @(x) isstring(x) || iscell(x) || ischar(x));
addParameter(parser, 'TimeMode', 'absolute', @(x) ischar(x) || isstring(x));
addParameter(parser, 'TimeWindow', [5 20], @(x) isempty(x) || (isnumeric(x) && numel(x) == 2));
addParameter(parser, 'RollbackZoom', [], @(x) isempty(x) || (isnumeric(x) && numel(x) == 2));
addParameter(parser, 'PlotTrajectory', true, @(x) islogical(x) || isnumeric(x));
addParameter(parser, 'TrajectoryTimeWindow', [], @(x) isempty(x) || (isnumeric(x) && numel(x) == 2));
addParameter(parser, 'TrajectoryShowPostpred', true, @(x) islogical(x) || isnumeric(x));
addParameter(parser, 'Dpi', 600, @(x) isscalar(x) && isnumeric(x));
parse(parser, varargin{:});
args = parser.Results;

scriptDir = fileparts(mfilename('fullpath'));
focus = double(args.Focus);
attacker = double(args.Attacker);

caseNames = normalizeStringArray(args.CaseNames);
if isempty(caseNames)
    caseNames = [
        "No rollback"
        "Rollback"
        "Rollback + anchoring"];
end

files = normalizeStringArray(args.Files);
if isempty(files) && logical(args.SelectFiles)
    files = selectCaseFiles(scriptDir, string(args.ResultDate), double(args.Host), caseNames);
elseif isempty(files)
    files = defaultCaseFiles(scriptDir, string(args.ResultDate));
end
if numel(files) ~= numel(caseNames)
    error('Number of files (%d) must match number of case names (%d).', numel(files), numel(caseNames));
end

cases = loadCases(files, caseNames, scriptDir, focus);
if ~isfinite(attacker)
    attacker = inferAttacker(cases, focus);
end
signalSpec = chooseRejectionSignal(cases, focus, attacker);
trustSpec = chooseTrustDropSignal(cases, focus, attacker);

style = paperStyle();
set(groot, 'defaultAxesFontName', style.fontName);
set(groot, 'defaultTextFontName', style.fontName);

timeWindow = double(args.TimeWindow);
rollbackZoom = double(args.RollbackZoom);
timeMode = normalizeTimeMode(args.TimeMode);
summary = buildSummary(cases, focus, attacker, signalSpec);
printSummary(summary, focus, attacker, signalSpec);

fig = makeMainFigure(cases, focus, attacker, signalSpec, trustSpec, style, timeWindow, rollbackZoom, timeMode);
if logical(args.PlotTrajectory)
    trajectoryFig = makeTrajectoryFigure(cases, focus, style, ...
        double(args.TrajectoryTimeWindow), timeMode, logical(args.TrajectoryShowPostpred));
else
    trajectoryFig = [];
end

outputDir = resolveOutputDir(args.OutputDir, scriptDir);
formats = normalizeStringArray(args.Formats);
if logical(args.Save)
    ensureFolder(outputDir);
    writetable(summary, fullfile(outputDir, sprintf('rollback_anchor_main_summary_V%d.csv', focus)));
end
finishFigure(fig, sprintf('rollback_anchor_main_V%d', focus), outputDir, formats, logical(args.Save), args.Dpi);
if ~isempty(trajectoryFig)
    finishFigure(trajectoryFig, sprintf('rollback_anchor_xy_trajectories_V%d', focus), ...
        outputDir, formats, logical(args.Save), args.Dpi);
end
if logical(args.Save)
    fprintf('Saved compact rollback/anchor figures to: %s\n', outputDir);
end
end

function fig = makeMainFigure(cases, focus, attacker, signalSpec, trustSpec, style, timeWindow, rollbackZoom, timeMode)
fig = figure('Name', 'Rollback and Anchoring Main Figure', 'Color', 'w', ...
    'Units', 'centimeters', 'Position', [2 2 18 20]);
layout = tiledlayout(fig, 4, 1, 'TileSpacing', 'compact', 'Padding', 'compact');

ax1 = nexttile(layout);
plotPositionErrorPanel(ax1, cases, focus, style, timeWindow, timeMode);

ax2 = nexttile(layout);
plotRejectionPanel(ax2, cases, attacker, signalSpec, style, timeWindow, timeMode);

ax3 = nexttile(layout);
plotTrustDropPanel(ax3, cases, attacker, trustSpec, style, timeWindow, timeMode);

ax4 = nexttile(layout);
plotRollbackCorrectionPanel(ax4, cases, focus, style, timeWindow, rollbackZoom, timeMode);

title(layout, sprintf('Rollback and anchoring effect for target V%d', focus), ...
    'FontName', style.fontName, 'FontSize', style.titleSize + 1, 'FontWeight', 'bold');
end

function fig = makeTrajectoryFigure(cases, focus, style, timeWindow, timeMode, showPostpred)
n = numel(cases);
figWidth = max(18, 6.2 * n);
fig = figure('Name', 'Rollback and Anchoring XY Trajectories', 'Color', 'w', ...
    'Units', 'centimeters', 'Position', [2 2 figWidth 7.8]);
layout = tiledlayout(fig, 1, n, 'TileSpacing', 'compact', 'Padding', 'compact');
xyLimits = trajectoryLimits(cases, focus, timeWindow, timeMode, showPostpred);

for i = 1:n
    ax = nexttile(layout);
    plotTrajectoryCasePanel(ax, cases(i), focus, style, xyLimits, timeWindow, ...
        timeMode, showPostpred, i);
end

title(layout, sprintf('XY trajectory comparison for target V%d', focus), ...
    'FontName', style.fontName, 'FontSize', style.titleSize + 1, ...
    'FontWeight', 'bold');
end

function plotTrajectoryCasePanel(ax, caseData, focus, style, xyLimits, timeWindow, timeMode, showPostpred, caseIndex)
hold(ax, 'on');
tbl = caseData.table;
t = caseTime(caseData, timeMode);
mask = trajectoryTimeMask(t, timeWindow);
colorIndex = mod(caseIndex - 1, size(style.caseColors, 1)) + 1;
caseColor = style.caseColors(colorIndex, :);

refX = col(tbl, sprintf('ref_x_%d', focus));
refY = col(tbl, sprintf('ref_y_%d', focus));
postX = col(tbl, sprintf('postpred_x_%d', focus));
postY = col(tbl, sprintf('postpred_y_%d', focus));
estX = col(tbl, sprintf('est_x_%d', focus));
estY = col(tbl, sprintf('est_y_%d', focus));

plotXYFinite(ax, refX(mask), refY(mask), '--', style.referenceColor, ...
    style.lineWidth, 'reference');
if showPostpred
    postColor = lightenColor(caseColor, 0.55);
    plotXYFinite(ax, postX(mask), postY(mask), ':', postColor, ...
        style.lineWidth, 'before rollback');
end
plotXYFinite(ax, estX(mask), estY(mask), '-', caseColor, ...
    style.lineWidth + 0.25, 'final estimate');

attackStart = eventTimeForMode(caseData.attackStart_s, caseData, timeMode);
attackEnd = eventTimeForMode(caseData.attackEnd_s, caseData, timeMode);
eventTime = eventTimeForMode(caseData.event.time_s, caseData, timeMode);
markXYEvent(ax, t, estX, estY, attackStart, 'o', style.attackColor, 'attack start');
markXYEvent(ax, t, estX, estY, attackEnd, 's', style.attackColor, 'attack end');
if caseData.event.rollback_triggered
    markXYEvent(ax, t, estX, estY, eventTime, '^', caseColor, 'rollback event');
end

if all(isfinite(xyLimits))
    xlim(ax, xyLimits(1:2));
    ylim(ax, xyLimits(3:4));
end
axis(ax, 'equal');
grid(ax, 'on');
ax.GridAlpha = style.gridAlpha;
ax.FontName = style.fontName;
ax.FontSize = style.fontSize;
ax.LineWidth = 0.8;
box(ax, 'on');
xlabel(ax, 'x [m]', 'FontSize', style.fontSize);
ylabel(ax, 'y [m]', 'FontSize', style.fontSize);

titleText = sprintf('(%c) %s', char('a' + caseIndex - 1), caseData.name);
if isfield(caseData, 'metrics') && isfinite(caseData.metrics.est_attack_rmse_m)
    titleText = sprintf('%s | RMSE %.3f m', titleText, caseData.metrics.est_attack_rmse_m);
end
title(ax, titleText, 'FontSize', style.titleSize, 'FontWeight', 'bold', ...
    'Interpreter', 'none');
legend(ax, 'Location', 'best', 'FontSize', style.fontSize - 1, ...
    'Interpreter', 'none');
end

function xyLimits = trajectoryLimits(cases, focus, timeWindow, timeMode, showPostpred)
allX = [];
allY = [];
for i = 1:numel(cases)
    tbl = cases(i).table;
    t = caseTime(cases(i), timeMode);
    mask = trajectoryTimeMask(t, timeWindow);
    if showPostpred
        prefixes = ["ref", "est", "postpred"];
    else
        prefixes = ["ref", "est"];
    end
    for k = 1:numel(prefixes)
        prefix = char(prefixes(k));
        x = col(tbl, sprintf('%s_x_%d', prefix, focus));
        y = col(tbl, sprintf('%s_y_%d', prefix, focus));
        valid = mask & isfinite(x) & isfinite(y);
        allX = [allX; x(valid)]; %#ok<AGROW>
        allY = [allY; y(valid)]; %#ok<AGROW>
    end
end

if isempty(allX) || isempty(allY)
    xyLimits = [0 1 0 1];
    return;
end

xMin = min(allX);
xMax = max(allX);
yMin = min(allY);
yMax = max(allY);
xPad = 0.08 * max(1e-6, xMax - xMin);
yPad = 0.08 * max(1e-6, yMax - yMin);
xyLimits = [xMin - xPad, xMax + xPad, yMin - yPad, yMax + yPad];
end

function mask = trajectoryTimeMask(t, timeWindow)
mask = isfinite(t);
if isempty(timeWindow)
    return;
end
if numel(timeWindow) == 2 && all(isfinite(timeWindow)) && timeWindow(2) > timeWindow(1)
    mask = mask & t >= timeWindow(1) & t <= timeWindow(2);
end
end

function eventTime = eventTimeForMode(rawEventTime, caseData, timeMode)
if ~isfinite(rawEventTime)
    eventTime = NaN;
elseif timeMode == "absolute"
    eventTime = rawEventTime;
else
    eventTime = rawEventTime - caseData.attackStart_s;
end
end

function plotXYFinite(ax, x, y, lineStyle, color, lineWidth, displayName)
mask = isfinite(x) & isfinite(y);
if any(mask)
    plot(ax, x(mask), y(mask), 'LineStyle', lineStyle, 'Color', color, ...
        'LineWidth', lineWidth, 'DisplayName', displayName);
end
end

function markXYEvent(ax, t, x, y, eventTime, marker, color, displayName)
[xEvent, yEvent] = nearestFinitePoint(t, x, y, eventTime);
if ~isfinite(xEvent) || ~isfinite(yEvent)
    return;
end
plot(ax, xEvent, yEvent, marker, 'Color', color, ...
    'MarkerFaceColor', 'w', 'MarkerSize', 5.5, 'LineWidth', 1.0, ...
    'DisplayName', displayName);
end

function [xEvent, yEvent] = nearestFinitePoint(t, x, y, eventTime)
xEvent = NaN;
yEvent = NaN;
if ~isfinite(eventTime)
    return;
end
mask = isfinite(t) & isfinite(x) & isfinite(y);
if ~any(mask)
    return;
end
idxs = find(mask);
[~, relIdx] = min(abs(t(idxs) - eventTime));
idx = idxs(relIdx);
xEvent = x(idx);
yEvent = y(idx);
end

function color = lightenColor(color, amount)
amount = min(max(amount, 0.0), 1.0);
color = color + amount * (1.0 - color);
color = min(max(color, 0.0), 1.0);
end

function plotPositionErrorPanel(ax, cases, focus, style, timeWindow, timeMode)
hold(ax, 'on');
for i = 1:numel(cases)
    err = positionErrorWithReference(cases(i).table, focus, 'est');
    plotFinite(ax, caseTime(cases(i), timeMode), err, '-', style.caseColors(i, :), style.lineWidth, cases(i).name);
end
markAttackAndRollback(ax, cases, style, false, timeMode);
applyTimeWindow(ax, timeWindow);
ylim(ax, paddedLimits(ax, [0 1]));
styleAxes(ax, '(a) Position-estimation error', timeAxisLabel(timeMode), ...
    'position error [m]', style);
legend(ax, 'Location', 'best', 'FontSize', style.fontSize - 1, 'Interpreter', 'none');
end

function plotRejectionPanel(ax, cases, attacker, signalSpec, style, timeWindow, timeMode)
hold(ax, 'on');
for i = 1:numel(cases)
    y = col(cases(i).table, signalSpec.column);
    plotFinite(ax, caseTime(cases(i), timeMode), y, '-', style.caseColors(i, :), style.lineWidth, cases(i).name);
end
markAttackAndRollback(ax, cases, style, false, timeMode);
applyTimeWindow(ax, timeWindow);
if signalSpec.isTrust
    yline(ax, 0.5, ':', 'Color', style.attackColor, 'LineWidth', 0.8, ...
        'DisplayName', 'trust threshold');
end
ylim(ax, paddedLimits(ax, [0 1]));
titleText = sprintf('(b) Attack rejection: %s', signalSpec.label);
if isfinite(attacker)
    titleText = sprintf('%s (V%d)', titleText, attacker);
end
styleAxes(ax, titleText, timeAxisLabel(timeMode), signalSpec.ylabel, style);
legend(ax, 'Location', 'best', 'FontSize', style.fontSize - 1, 'Interpreter', 'none');
end

function plotTrustDropPanel(ax, cases, attacker, trustSpec, style, timeWindow, timeMode)
hold(ax, 'on');
for i = 1:numel(cases)
    y = col(cases(i).table, trustSpec.column);
    plotFinite(ax, caseTime(cases(i), timeMode), y, '-', style.caseColors(i, :), style.lineWidth, cases(i).name);
end
markAttackAndRollback(ax, cases, style, false, timeMode);
applyTimeWindow(ax, timeWindow);
yline(ax, 0.5, ':', 'Color', style.attackColor, 'LineWidth', 0.8, ...
    'DisplayName', 'trust threshold');
ylim(ax, paddedLimits(ax, [0 1]));
titleText = sprintf('(c) Trust drop: %s', trustSpec.label);
if isfinite(attacker)
    titleText = sprintf('%s (V%d)', titleText, attacker);
end
styleAxes(ax, titleText, timeAxisLabel(timeMode), 'trust [-]', style);
legend(ax, 'Location', 'best', 'FontSize', style.fontSize - 1, 'Interpreter', 'none');
end

function plotRollbackCorrectionPanel(ax, cases, focus, style, timeWindow, rollbackZoom, timeMode)
hold(ax, 'on');
plotted = false;
for i = 2:numel(cases)
    post = positionErrorWithReference(cases(i).table, focus, 'postpred');
    est = positionErrorWithReference(cases(i).table, focus, 'est');
    color = style.caseColors(i, :);
    t = caseTime(cases(i), timeMode);
    plotFinite(ax, t, post, '--', color, style.lineWidth, sprintf('%s before', cases(i).name));
    plotFinite(ax, t, est, '-', color, style.lineWidth, sprintf('%s after', cases(i).name));
    plotted = true;
end
if ~plotted
    text(ax, 0.5, 0.5, 'No rollback cases available', 'Units', 'normalized', ...
        'HorizontalAlignment', 'center', 'FontName', style.fontName, 'FontSize', style.fontSize);
end
markAttackAndRollback(ax, cases, style, true, timeMode);
zoomWindow = resolveRollbackZoom(cases, rollbackZoom, timeWindow, timeMode);
applyTimeWindow(ax, zoomWindow);
ylim(ax, paddedLimits(ax, [0 1]));
if isempty(rollbackZoom)
    titleText = '(d) Rollback correction';
else
    titleText = '(d) Rollback correction zoom';
end
styleAxes(ax, titleText, timeAxisLabel(timeMode), ...
    'position error [m]', style);
annotateRollbackCorrection(ax, cases, style);
legend(ax, 'Location', 'northwest', 'FontSize', style.fontSize - 1, 'Interpreter', 'none');
end

function files = selectCaseFiles(scriptDir, resultDate, hostId, caseNames)
rootDir = fullfile(scriptDir, 'results');
resultDate = strtrim(string(resultDate));
if strlength(resultDate) == 0
    startDir = rootDir;
else
    startDir = fullfile(rootDir, resultDate);
    if ~isfolder(startDir)
        startDir = rootDir;
    end
end
if ~isfolder(startDir)
    error('Results folder does not exist: %s', rootDir);
end

files = strings(numel(caseNames), 1);
for k = 1:numel(caseNames)
    [selected, selectedPath] = uigetfile( ...
        fullfile(startDir, sprintf('trust_weight_log_V%d*.csv', hostId)), ...
        sprintf('Select CSV for %s', caseNames(k)));
    if isequal(selected, 0)
        error('File selection cancelled.');
    end
    files(k) = erase(string(fullfile(selectedPath, selected)), string(scriptDir) + filesep);
end

fprintf('\nSelected compact figure files:\n');
for k = 1:numel(files)
    fprintf('  %s -> %s\n', caseNames(k), files(k));
end
fprintf('\n');
end

function files = defaultCaseFiles(scriptDir, resultDate)
resultDate = strtrim(string(resultDate));
if strlength(resultDate) == 0
    resultDate = "02-07-26";
end

files = [
    fullfile('results', resultDate, 'case2', 'trust_weight_log_V1_15-32-26_977725.csv')
    fullfile('results', resultDate, 'case2', 'trust_weight_log_V1_15-33-59_274476.csv')
    fullfile('results', resultDate, 'case2', 'trust_weight_log_V1_15-35-25_102224.csv')];

if all(isfile(fullfile(scriptDir, files)))
    return;
end

error(['Default compact-figure files are missing. Pass ''Files'' explicitly ', ...
    'in this order: no rollback, rollback, rollback + anchoring.']);
end

function cases = loadCases(files, caseNames, scriptDir, focus)
cases = repmat(struct(), numel(files), 1);
for i = 1:numel(files)
    filepath = resolveInputFile(files(i), scriptDir);
    tbl = readTrustTable(filepath);
    if ~ismember('time', tbl.Properties.VariableNames)
        error('Missing time column in %s.', filepath);
    end
    if ~ismember(sprintf('est_x_%d', focus), tbl.Properties.VariableNames)
        error('Focus vehicle V%d is not present in %s.', focus, filepath);
    end

    cases(i).name = caseNames(i);
    cases(i).file = string(filepath);
    cases(i).relativeFile = erase(string(filepath), string(scriptDir) + filesep);
    cases(i).table = tbl;
    cases(i).rawTime = col(tbl, 'time');
    [cases(i).attackStart_s, cases(i).attackEnd_s] = attackWindow(tbl, focus);
    cases(i).time = cases(i).rawTime - cases(i).attackStart_s;
    cases(i).event = correctionEvent(tbl, focus, cases(i).attackStart_s);
    cases(i).metrics = attackMetrics(tbl, focus, cases(i).attackStart_s, cases(i).attackEnd_s);
end
end

function filepath = resolveInputFile(fileArg, scriptDir)
filepath = char(fileArg);
if isfile(filepath)
    return;
end

candidate = fullfile(scriptDir, filepath);
if isfile(candidate)
    filepath = candidate;
    return;
end

candidate = fullfile(scriptDir, 'results', filepath);
if isfile(candidate)
    filepath = candidate;
    return;
end

error('File does not exist: %s', filepath);
end

function tbl = readTrustTable(filepath)
opts = detectImportOptions(filepath, 'VariableNamingRule', 'preserve');
try
    opts = setvaropts(opts, opts.VariableNames, 'WhitespaceRule', 'preserve');
catch
end
try
    opts = setvaropts(opts, opts.VariableNames, 'EmptyFieldRule', 'auto');
catch
end
tbl = readtable(filepath, opts);
end

function [attackStart_s, attackEnd_s] = attackWindow(tbl, focus)
startCandidates = [
    firstFinite(col(tbl, 'v2v_attack_start_s'))
    firstFinite(col(tbl, sprintf('inject_attack_start_%d', focus)))];
endCandidates = [
    firstFinite(col(tbl, 'v2v_attack_end_s'))
    firstFinite(col(tbl, sprintf('inject_attack_end_%d', focus)))];

attackStart_s = firstFinite(startCandidates);
attackEnd_s = firstFinite(endCandidates);
if ~isfinite(attackStart_s)
    attackStart_s = 0;
end
if ~isfinite(attackEnd_s) || attackEnd_s <= attackStart_s
    attackEnd_s = NaN;
end
end

function metrics = attackMetrics(tbl, focus, attackStart_s, attackEnd_s)
t = col(tbl, 'time');
post = positionErrorWithReference(tbl, focus, 'postpred');
est = positionErrorWithReference(tbl, focus, 'est');

if isfinite(attackEnd_s)
    mask = t >= attackStart_s & t <= attackEnd_s;
else
    mask = t >= attackStart_s;
end

metrics = struct();
metrics.post_attack_rmse_m = rmse(post(mask));
metrics.est_attack_rmse_m = rmse(est(mask));
metrics.post_attack_max_m = maxOrNan(post(mask));
metrics.est_attack_max_m = maxOrNan(est(mask));
metrics.attack_duration_s = attackEnd_s - attackStart_s;
end

function event = correctionEvent(tbl, focus, attackStart_s)
t = col(tbl, 'time');
post = positionErrorWithReference(tbl, focus, 'postpred');
est = positionErrorWithReference(tbl, focus, 'est');
rb = col(tbl, 'rollback_triggered');
enabled = maxFinite(col(tbl, 'rollback_enabled'));
correction = post - est;

mask = isfinite(t) & isfinite(post) & isfinite(est);
rbMask = mask & isfinite(rb) & rb > 0;
if any(rbMask)
    idxs = find(rbMask);
    [~, relIdx] = max(correction(idxs));
    idx = idxs(relIdx);
elseif any(mask)
    idxs = find(mask);
    [~, relIdx] = max(correction(idxs));
    idx = idxs(relIdx);
else
    idx = NaN;
end

event = struct();
event.index = idx;
event.rollback_enabled = isfinite(enabled) && enabled > 0;
event.rollback_triggered = false;
event.rollback_count = nnz(isfinite(rb) & rb > 0);
event.time_s = NaN;
event.time_from_attack_s = NaN;
event.postpred_pos_err_m = NaN;
event.est_pos_err_m = NaN;
event.correction_m = 0;
event.correction_percent = 0;

if isfinite(idx)
    event.rollback_triggered = isfinite(rb(idx)) && rb(idx) > 0;
    event.time_s = t(idx);
    event.time_from_attack_s = t(idx) - attackStart_s;
    event.postpred_pos_err_m = post(idx);
    event.est_pos_err_m = est(idx);
    event.correction_m = correction(idx);
    if post(idx) > 0
        event.correction_percent = 100 * correction(idx) / post(idx);
    end
end
end

function attacker = inferAttacker(cases, focus)
attacker = NaN;
for i = 1:numel(cases)
    attacker = firstFinite(col(cases(i).table, sprintf('inject_attack_attacker_%d', focus)));
    if isfinite(attacker)
        attacker = round(attacker);
        return;
    end
end

for i = 1:numel(cases)
    names = string(cases(i).table.Properties.VariableNames);
    mask = startsWith(names, "inject_attack_attacker_");
    attackCols = names(mask);
    for k = 1:numel(attackCols)
        attacker = firstFinite(col(cases(i).table, attackCols(k)));
        if isfinite(attacker)
            attacker = round(attacker);
            return;
        end
    end
end
end

function spec = chooseRejectionSignal(cases, focus, attacker)
spec = struct();
spec.column = "";
spec.label = "unavailable";
spec.ylabel = "signal [-]";
spec.isTrust = false;

if isfinite(attacker)
    attacker = round(attacker);
    if attacker == focus
        candidate = sprintf('w0_final_%d', focus);
        if hasColumnAny(cases, candidate)
            spec.column = candidate;
            spec.label = "direct attacked-source weight";
            spec.ylabel = "weight [-]";
            return;
        end
    end

    candidate = sprintf('w_neighbor_from_v%d_to_%d', attacker, focus);
    if hasColumnAny(cases, candidate)
        spec.column = candidate;
        spec.label = "attacker source weight";
        spec.ylabel = "weight [-]";
        return;
    end

    candidate = sprintf('trust_%d', attacker);
    if hasColumnAny(cases, candidate)
        spec.column = candidate;
        spec.label = "attacker trust";
        spec.ylabel = "trust [-]";
        spec.isTrust = true;
        return;
    end
end

candidate = sprintf('w0_final_%d', focus);
if hasColumnAny(cases, candidate)
    spec.column = candidate;
    spec.label = "target direct weight";
    spec.ylabel = "weight [-]";
    return;
end

candidate = sprintf('w_neighbor_sum_final_%d', focus);
if hasColumnAny(cases, candidate)
    spec.column = candidate;
    spec.label = "target neighbor total weight";
    spec.ylabel = "weight [-]";
    return;
end

candidate = sprintf('trust_%d', focus);
if hasColumnAny(cases, candidate)
    spec.column = candidate;
    spec.label = "target trust";
    spec.ylabel = "trust [-]";
    spec.isTrust = true;
    return;
end

error('Could not find a rejection signal column for target V%d.', focus);
end

function spec = chooseTrustDropSignal(cases, focus, attacker)
spec = struct();
spec.column = "";
spec.label = "unavailable";

if isfinite(attacker)
    vehicle = round(attacker);
else
    vehicle = focus;
end

candidatePairs = {
    sprintf('gtrust_%d', vehicle), 'generalized trust'
    sprintf('trust_%d', vehicle), 'final trust'
    sprintf('local_trust_%d', vehicle), 'local trust'
    sprintf('global_trust_%d', vehicle), 'global trust'};

for i = 1:size(candidatePairs, 1)
    candidate = candidatePairs{i, 1};
    if hasColumnAny(cases, candidate)
        spec.column = candidate;
        spec.label = candidatePairs{i, 2};
        return;
    end
end

error('Could not find a trust-drop signal column for V%d.', vehicle);
end

function tf = hasColumnAny(cases, columnName)
tf = false;
for i = 1:numel(cases)
    if ismember(char(columnName), cases(i).table.Properties.VariableNames)
        tf = true;
        return;
    end
end
end

function summary = buildSummary(cases, focus, attacker, signalSpec)
n = numel(cases);
caseName = strings(n, 1);
file = strings(n, 1);
focusVehicle = repmat(focus, n, 1);
attackerVehicle = repmat(attacker, n, 1);
rollbackEnabled = false(n, 1);
rollbackTriggeredRows = zeros(n, 1);
attackStart_s = nan(n, 1);
attackEnd_s = nan(n, 1);
rollbackEventTimeFromAttack_s = nan(n, 1);
postpredPosErr_m = nan(n, 1);
estPosErr_m = nan(n, 1);
correction_m = nan(n, 1);
correction_percent = nan(n, 1);
postAttackRmse_m = nan(n, 1);
finalAttackRmse_m = nan(n, 1);
finalAttackMax_m = nan(n, 1);
rejectionSignalMean = nan(n, 1);
rejectionSignalMin = nan(n, 1);
rejectionSignalMax = nan(n, 1);

for i = 1:n
    tbl = cases(i).table;
    t = col(tbl, 'time');
    if isfinite(cases(i).attackEnd_s)
        attackMask = t >= cases(i).attackStart_s & t <= cases(i).attackEnd_s;
    else
        attackMask = t >= cases(i).attackStart_s;
    end
    signal = col(tbl, signalSpec.column);

    event = cases(i).event;
    metrics = cases(i).metrics;
    caseName(i) = cases(i).name;
    file(i) = cases(i).relativeFile;
    rollbackEnabled(i) = event.rollback_enabled;
    rollbackTriggeredRows(i) = event.rollback_count;
    attackStart_s(i) = cases(i).attackStart_s;
    attackEnd_s(i) = cases(i).attackEnd_s;
    if event.rollback_triggered
        rollbackEventTimeFromAttack_s(i) = event.time_from_attack_s;
        postpredPosErr_m(i) = event.postpred_pos_err_m;
        estPosErr_m(i) = event.est_pos_err_m;
        correction_m(i) = event.correction_m;
        correction_percent(i) = event.correction_percent;
    else
        correction_m(i) = 0;
        correction_percent(i) = 0;
    end
    postAttackRmse_m(i) = metrics.post_attack_rmse_m;
    finalAttackRmse_m(i) = metrics.est_attack_rmse_m;
    finalAttackMax_m(i) = metrics.est_attack_max_m;
    rejectionSignalMean(i) = finiteMean(signal(attackMask));
    rejectionSignalMin(i) = finiteMin(signal(attackMask));
    rejectionSignalMax(i) = finiteMax(signal(attackMask));
end

rejectionSignal = repmat(string(signalSpec.column), n, 1);
summary = table(caseName, focusVehicle, attackerVehicle, rollbackEnabled, ...
    rollbackTriggeredRows, attackStart_s, attackEnd_s, rollbackEventTimeFromAttack_s, ...
    postpredPosErr_m, estPosErr_m, correction_m, correction_percent, ...
    postAttackRmse_m, finalAttackRmse_m, finalAttackMax_m, ...
    rejectionSignal, rejectionSignalMean, rejectionSignalMin, rejectionSignalMax, file);
end

function printSummary(summary, focus, attacker, signalSpec)
fprintf('\nCompact rollback/anchor summary for target V%d', focus);
if isfinite(attacker)
    fprintf(' under attacker/source V%d', attacker);
end
fprintf('\n');
fprintf('Rejection signal: %s (%s)\n', char(signalSpec.label), char(signalSpec.column));
fprintf('--------------------------------------------------------------------------------\n');
for i = 1:height(summary)
    fprintf('%d) %s\n', i, summary.caseName(i));
    fprintf('   final attack RMSE %.3f m | max %.3f m | rejection mean %.3f\n', ...
        summary.finalAttackRmse_m(i), summary.finalAttackMax_m(i), ...
        summary.rejectionSignalMean(i));
    if isfinite(summary.rollbackEventTimeFromAttack_s(i))
        fprintf('   rollback t-attack %.4f s | post %.3f m -> final %.3f m | corrected %.3f m (%.1f%%)\n', ...
            summary.rollbackEventTimeFromAttack_s(i), summary.postpredPosErr_m(i), ...
            summary.estPosErr_m(i), summary.correction_m(i), summary.correction_percent(i));
    else
        fprintf('   no rollback correction event\n');
    end
end
fprintf('--------------------------------------------------------------------------------\n\n');
end

function annotateRollbackCorrection(ax, cases, style)
lines = strings(0, 1);
for i = 2:numel(cases)
    event = cases(i).event;
    if event.rollback_triggered && isfinite(event.postpred_pos_err_m)
        if i == 2
            label = "RB";
        elseif i == 3
            label = "RB+anchor";
        else
            label = sprintf('Case %d', i);
        end
        lines(end + 1, 1) = sprintf('%s: %.3f -> %.3f m (%.1f%%)', ...
            label, event.postpred_pos_err_m, event.est_pos_err_m, ...
            event.correction_percent); %#ok<AGROW>
    end
end
if isempty(lines)
    return;
end
text(ax, 0.98, 0.96, strjoin(lines, newline), 'Units', 'normalized', ...
    'HorizontalAlignment', 'right', 'VerticalAlignment', 'top', 'FontName', style.fontName, ...
    'FontSize', style.fontSize - 1, 'Color', style.eventColor, ...
    'BackgroundColor', [1 1 1], 'Margin', 3, 'Interpreter', 'none');
end

function markAttackAndRollback(ax, cases, style, showRollback, timeMode)
if isempty(cases)
    return;
end
if timeMode == "absolute"
    attackStart = cases(1).attackStart_s;
    attackEnd = cases(1).attackEnd_s;
else
    attackStart = 0;
    attackEnd = cases(1).attackEnd_s - cases(1).attackStart_s;
end
xline(ax, attackStart, '-', 'Color', style.attackColor, 'LineWidth', 0.9, ...
    'HandleVisibility', 'off');
if isfinite(attackEnd) && attackEnd > attackStart
    xline(ax, attackEnd, '-', 'Color', style.attackColor, 'LineWidth', 0.9, ...
        'HandleVisibility', 'off');
end

if ~showRollback
    return;
end

for i = 1:numel(cases)
    if timeMode == "absolute"
        eventTime = cases(i).event.time_s;
    else
        eventTime = cases(i).event.time_from_attack_s;
    end
    if cases(i).event.rollback_triggered && isfinite(eventTime)
        xline(ax, eventTime, ':', 'Color', style.caseColors(i, :), ...
            'LineWidth', 0.9, 'HandleVisibility', 'off');
    end
end
end

function zoomWindow = resolveRollbackZoom(cases, rollbackZoom, timeWindow, timeMode)
center = NaN;
for i = 2:numel(cases)
    if timeMode == "absolute"
        candidate = cases(i).event.time_s;
    else
        candidate = cases(i).event.time_from_attack_s;
    end
    if cases(i).event.rollback_triggered && isfinite(candidate)
        center = candidate;
        break;
    end
end

if isfinite(center) && numel(rollbackZoom) == 2 && all(isfinite(rollbackZoom))
    zoomWindow = center + rollbackZoom;
elseif ~isempty(timeWindow)
    zoomWindow = timeWindow;
else
    zoomWindow = [];
end
end

function timeMode = normalizeTimeMode(value)
value = lower(strtrim(string(value)));
if any(value == ["absolute", "abs", "normal", "raw"])
    timeMode = "absolute";
elseif any(value == ["relative", "rel", "attack"])
    timeMode = "relative";
else
    error('Unsupported TimeMode "%s". Use "absolute" or "relative".', value);
end
end

function t = caseTime(caseData, timeMode)
if timeMode == "absolute"
    t = caseData.rawTime;
else
    t = caseData.time;
end
end

function label = timeAxisLabel(timeMode)
if timeMode == "absolute"
    label = 'time [s]';
else
    label = 'time from attack start [s]';
end
end

function err = positionErrorWithReference(tbl, focus, prefix)
err = col(tbl, sprintf('%s_pos_err_%d', prefix, focus));
if any(isfinite(err))
    return;
end

x = col(tbl, sprintf('%s_x_%d', prefix, focus));
y = col(tbl, sprintf('%s_y_%d', prefix, focus));
refX = col(tbl, sprintf('ref_x_%d', focus));
refY = col(tbl, sprintf('ref_y_%d', focus));
mask = isfinite(x) & isfinite(y) & isfinite(refX) & isfinite(refY);
err = nan(size(x));
err(mask) = hypot(x(mask) - refX(mask), y(mask) - refY(mask));
end

function plotFinite(ax, x, y, lineStyle, color, lineWidth, displayName)
mask = isfinite(x) & isfinite(y);
if any(mask)
    plot(ax, x(mask), y(mask), 'LineStyle', lineStyle, 'Color', color, ...
        'LineWidth', lineWidth, 'DisplayName', displayName);
end
end

function values = normalizeStringArray(values)
if ischar(values)
    values = string({values});
elseif iscell(values)
    values = string(values(:));
else
    values = string(values(:));
end
values = values(strlength(values) > 0);
end

function y = col(tbl, name)
name = char(name);
if ismember(name, tbl.Properties.VariableNames)
    raw = tbl.(name);
    if isnumeric(raw)
        y = double(raw);
    elseif islogical(raw)
        y = double(raw);
    elseif iscell(raw)
        y = str2double(string(raw));
    else
        y = str2double(string(raw));
    end
else
    y = nan(height(tbl), 1);
end
y = y(:);
end

function value = firstFinite(values)
values = values(:);
idx = find(isfinite(values), 1, 'first');
if isempty(idx)
    value = NaN;
else
    value = values(idx);
end
end

function value = maxFinite(values)
values = values(isfinite(values));
if isempty(values)
    value = NaN;
else
    value = max(values);
end
end

function value = maxOrNan(values)
values = values(isfinite(values));
if isempty(values)
    value = NaN;
else
    value = max(values);
end
end

function value = rmse(values)
values = values(isfinite(values));
if isempty(values)
    value = NaN;
else
    value = sqrt(mean(values .^ 2));
end
end

function value = finiteMean(values)
values = values(isfinite(values));
if isempty(values)
    value = NaN;
else
    value = mean(values);
end
end

function value = finiteMin(values)
values = values(isfinite(values));
if isempty(values)
    value = NaN;
else
    value = min(values);
end
end

function value = finiteMax(values)
values = values(isfinite(values));
if isempty(values)
    value = NaN;
else
    value = max(values);
end
end

function lim = paddedLimits(ax, fallback)
children = findobj(ax, 'Type', 'line');
y = [];
for i = 1:numel(children)
    y = [y; children(i).YData(:)]; %#ok<AGROW>
end
y = y(isfinite(y));
if isempty(y)
    lim = fallback;
    return;
end
yMin = min(y);
yMax = max(y);
pad = 0.08 * max(1e-6, yMax - yMin);
lim = [min(fallback(1), yMin - pad), max(fallback(2), yMax + pad)];
end

function styleAxes(ax, titleText, xlabelText, ylabelText, style)
title(ax, titleText, 'FontSize', style.titleSize, 'FontWeight', 'bold');
xlabel(ax, xlabelText, 'FontSize', style.fontSize);
ylabel(ax, ylabelText, 'FontSize', style.fontSize);
grid(ax, 'on');
ax.GridAlpha = style.gridAlpha;
ax.FontName = style.fontName;
ax.FontSize = style.fontSize;
ax.LineWidth = 0.8;
box(ax, 'on');
end

function applyTimeWindow(ax, timeWindow)
if isempty(timeWindow)
    return;
end
if numel(timeWindow) == 2 && all(isfinite(timeWindow)) && timeWindow(2) > timeWindow(1)
    xlim(ax, timeWindow);
end
end

function outputDir = resolveOutputDir(outputDirArg, scriptDir)
outputDir = char(outputDirArg);
if isempty(outputDir)
    outputDir = fullfile(scriptDir, 'paper_figures');
elseif ~isfolder(outputDir) && ~contains(outputDir, filesep) && ~contains(outputDir, '/')
    outputDir = fullfile(scriptDir, outputDir);
end
end

function ensureFolder(folder)
if ~isfolder(folder)
    mkdir(folder);
end
end

function finishFigure(fig, name, outputDir, formats, shouldSave, dpi)
set(fig, 'Renderer', 'painters');
if ~shouldSave
    return;
end
ensureFolder(outputDir);
for i = 1:numel(formats)
    fmt = lower(strtrim(formats(i)));
    out = fullfile(outputDir, string(name) + "." + fmt);
    switch fmt
        case "pdf"
            exportgraphics(fig, out, 'ContentType', 'vector');
        case "png"
            exportgraphics(fig, out, 'Resolution', dpi);
        otherwise
            warning('Unsupported export format "%s"; skipping.', fmt);
    end
end
end

function style = paperStyle()
style.fontName = 'Times New Roman';
style.fontSize = 9;
style.titleSize = 10;
style.lineWidth = 1.35;
style.caseColors = [
    0.0000 0.4470 0.7410
    0.8500 0.3250 0.0980
    0.1000 0.5500 0.3000
    0.4940 0.1840 0.5560
    0.3010 0.7450 0.9330];
style.referenceColor = [0.10 0.10 0.10];
style.attackColor = [0.45 0.45 0.45];
style.eventColor = [0.15 0.15 0.15];
style.gridAlpha = 0.20;
end
