"""
Plotter for Trust and Weight Logger

Interactive script used to plot `trust_weight_log_V*.csv` generated by `trust_logger.py`.
"""

import os
import glob
import pandas as pd
import matplotlib.pyplot as plt


def main():
    directory = os.path.dirname(os.path.abspath(__file__))
    csv_files = glob.glob(os.path.join(directory, "trust_weight_log_V*.csv"))

    if not csv_files:
        print("No trust log files found in:", directory)
        return

    print("Found files:")
    for i, f in enumerate(csv_files):
        print(f"[{i}] {os.path.basename(f)}")

    choice = input(f"Select file to plot [0-{len(csv_files) - 1}]: ").strip()
    try:
        choice = int(choice)
        file_to_plot = csv_files[choice]
    except (ValueError, IndexError):
        print("Invalid choice. Exiting.")
        return

    df = pd.read_csv(file_to_plot)
    if "time" not in df.columns:
        print("Invalid format: 'time' column missing.")
        return

    times = df["time"].values

    # Identify active neighbors
    active_neighbors = []
    max_vehicles = 10
    for i in range(max_vehicles):
        trust_col = f"trust_{i}"
        weight_col = f"w_neighbor_{i}"
        if trust_col in df.columns and weight_col in df.columns:
            # Check if this neighbor actually has valid dynamic data
            if df[weight_col].max() > 0 or df[trust_col].std() > 0:
                active_neighbors.append(i)

    if not active_neighbors:
        print("No active neighbor data found.")
        return

    fig, axes = plt.subplots(3, 1, figsize=(12, 10), sharex=True)

    for i in active_neighbors:
        axes[0].plot(times, df[f"trust_{i}"], label=f"Vehicle {i}")
    axes[0].set_title("Trust Scores")
    axes[0].set_ylabel("Trust [0, 1]")
    axes[0].grid(True)
    axes[0].legend()

    for i in active_neighbors:
        axes[1].plot(times, df[f"w_neighbor_{i}"], label=f"Weight {i}")
    if "w_self" in df.columns:
        axes[1].plot(times, df["w_self"], "k--", label="w_self")
    axes[1].set_title("Consensus Weights")
    axes[1].set_ylabel("Weight")
    axes[1].grid(True)
    axes[1].legend()

    # Trust components for the first active neighbor
    n_idx = active_neighbors[0]
    axes[2].plot(times, df[f"v_score_{n_idx}"], label="Velocity")
    axes[2].plot(times, df[f"d_score_{n_idx}"], label="Distance")
    axes[2].plot(times, df[f"a_score_{n_idx}"], label="Accel")
    axes[2].plot(times, df[f"h_score_{n_idx}"], label="Heading")
    axes[2].plot(times, df[f"b_score_{n_idx}"], label="Beacon")
    axes[2].set_title(f"Trust Components (Vehicle {n_idx})")
    axes[2].set_xlabel("Time [s]")
    axes[2].set_ylabel("Score [0, 1]")
    axes[2].grid(True)
    axes[2].legend()

    plt.tight_layout()
    plt.show()


if __name__ == "__main__":
    main()
