"""
Plotter for Trust and Weight Logger

Interactive script used to plot `trust_weight_log_V*.csv` generated by `trust_logger.py`.

Three separate figures with GridSpec layout:
  Figure 1 – Trust Calculation (component scores, local/global, final trust, flags)
  Figure 2 – Weight Calculation  (w0, w_self, w_neighbor, summary metrics)
  Figure 3 – State Estimation     (estimated states, confidence, prediction mode)
  Figure 4 – Max Impact Histograms
  Figure 5 – V2V Detailed Tracking (per-vehicle distances and element values)
"""

import os
import glob
import re
import math
import csv
import time
from typing import Dict, List, Tuple

import matplotlib.pyplot as plt
import matplotlib.gridspec as gridspec
import numpy as np
import argparse

# python plot_trust_data.py --file ".\trust_weight_log_V1.csv" --relative-file "..\Relative_obs\relative_uio_log_V1.csv"

# ──────────────────────────────────────────────────────────────────────
# Helpers
# ──────────────────────────────────────────────────────────────────────

def _load_csv(filepath: str) -> Tuple[List[str], List[Dict[str, str]]]:
    """Return (columns, rows-as-dicts) from a CSV file, filtering corrupt lines."""
    cleaned_lines = []
    with open(filepath, "r", encoding="utf-8", errors="replace") as f:
        for line in f:
            # Remove null bytes which can result from abrupt process termination
            line = line.replace('\x00', '')
            # Skip any lines that are still absurdly long (corrupted)
            if len(line) < 131072:
                cleaned_lines.append(line)
                
    reader = csv.DictReader(cleaned_lines)
    columns = reader.fieldnames or []
    rows = list(reader)
    return columns, rows


def _col_to_array(rows: List[dict], col: str) -> np.ndarray:
    """Convert a column to a float numpy array (NaN for missing/bad)."""
    vals = []
    for row in rows:
        raw = row.get(col, "")
        try:
            vals.append(float(raw))
        except (ValueError, TypeError):
            vals.append(float("nan"))
    return np.array(vals, dtype=float)


def _extract_vehicle_ids(columns: List[str]) -> List[int]:
    ids = set()
    prefixes = {
        "vehicle_present", "trust", "gtrust", "w_neighbor",
        "est_conf", "pred_mode", "est_x", "est_v",
        "v_score", "d_score", "a_score", "h_score",
        "b_score", "q_factor", "local_trust", "global_trust",
        "gamma_host", "gamma_local_peer", "gamma_self",
        "d_host_mean", "d_local_mean", "d_self",
        "mi_dist", "mi_veh_id", "mi_elem_idx", "mi_elem_val",
    }
    for col in columns:
        m = re.search(r"_(\d+)$", col)
        if m and col[: m.start()] in prefixes:
            ids.add(int(m.group(1)))
    return sorted(ids)


def _active_vehicles(rows: List[dict], columns: List[str],
                     vehicle_ids: List[int]) -> List[int]:
    active = []
    for vid in vehicle_ids:
        for prefix in ("vehicle_present", "trust", "gtrust",
                       "w_neighbor", "est_conf", "est_x"):
            col = f"{prefix}_{vid}"
            if col not in columns:
                continue
            arr = _col_to_array(rows, col)
            if prefix == "vehicle_present" and np.nanmax(arr) > 0:
                active.append(vid)
                break
            elif prefix != "vehicle_present" and np.any(np.isfinite(arr)):
                active.append(vid)
                break
    return active


def _plot_series(ax, times, rows, prefix, vids, label_fmt="Vehicle {}",
                 **kwargs):
    """Plot one series per vehicle. Returns count of plotted curves."""
    n = 0
    for vid in vids:
        col = f"{prefix}_{vid}"
        arr = _col_to_array(rows, col)
        if np.any(np.isfinite(arr)):
            ax.plot(times, arr, label=label_fmt.format(vid), **kwargs)
            n += 1
    return n


def _no_data(ax, title: str):
    ax.set_title(title, fontsize=10, fontweight="bold")
    ax.text(0.5, 0.5, "No data", ha="center", va="center",
            transform=ax.transAxes, fontsize=11, color="#888")


def _style(ax, title="", ylabel="", xlabel="", legend=True):
    if title:
        ax.set_title(title, fontsize=10, fontweight="bold")
    if ylabel:
        ax.set_ylabel(ylabel, fontsize=9)
    if xlabel:
        ax.set_xlabel(xlabel, fontsize=9)
    ax.grid(True, linestyle="--", alpha=0.4)
    ax.tick_params(labelsize=8)
    if legend:
        handles, labels = ax.get_legend_handles_labels()
        if handles:
            # Avoid duplicate legend entries for Turn Section if plotted multiple times
            by_label = dict(zip(labels, handles))
            ax.legend(by_label.values(), by_label.keys(), fontsize=7, ncol=max(1, len(by_label) // 2),
                      loc="best", framealpha=0.7)

def _add_turn_sections(ax, times, rows):
    is_turning = _col_to_array(rows, "is_turning")
    if np.any(np.isfinite(is_turning)) and np.any(is_turning > 0):
        import matplotlib.transforms as mtransforms
        trans = mtransforms.blended_transform_factory(ax.transData, ax.transAxes)
        ax.fill_between(times, 0, 1, where=(is_turning >= 1), color='gold', alpha=0.25, transform=trans, label='Turn Section')


def _yolo_usage_mask(rows: List[dict], vid: int) -> np.ndarray:
    """Return boolean mask where YOLO relative measurement was used for global trust."""
    yolo_flag = _col_to_array(rows, f"yolo_rel_meas_used_global_{vid}")
    if not np.any(np.isfinite(yolo_flag)):
        return np.zeros(len(rows), dtype=bool)
    return np.isfinite(yolo_flag) & (yolo_flag >= 0.5)


def _find_relative_uio_log(directory: str, host_id: int) -> str:
    """Return the matching relative UIO log for a host vehicle, if present."""
    if host_id < 0:
        return ""
    candidate_dirs = [
        directory,
        os.path.abspath(os.path.join(directory, "..", "Relative_obs")),
    ]
    matches = []
    for candidate_dir in candidate_dirs:
        pattern = os.path.join(candidate_dir, f"relative_uio_log_V{host_id}*.csv")
        matches.extend(glob.glob(pattern))
    matches = sorted(set(matches), key=os.path.getmtime)
    return matches[-1] if matches else ""

# ──────────────────────────────────────────────────────────────────────
# Figure builders
# ──────────────────────────────────────────────────────────────────────

def _fig_trust(times, rows, active, focus, host_id):
    """
    Figure 1 - Trust Calculation
    Layout (3 rows x 4 cols):
      [0,0] Direct trust                      [0,1] Generalized trust O_i(j)  [0,2] Local trust               [0,3] Global trust
      [1,0] Component scores (focus vehicle)  [1,1] Global trust factors      [1,2] Mahalanobis distances     [1,3] Attack flags
      [2,0] Relative distance comparison       [2,1] 
      [2,2] YOLO-vs-true relative errors       [2,3] Relative measurement usage flags
    """
    fig = plt.figure(figsize=(24, 12))
    fig.suptitle(f"Trust Calculation  (Host V{host_id})", fontsize=15,
                 fontweight="bold")
    gs = gridspec.GridSpec(3, 4, figure=fig, hspace=0.35, wspace=0.25)

    # (0,0) Direct trust
    ax = fig.add_subplot(gs[0, 0])
    if _plot_series(ax, times, rows, "trust", active) == 0:
        _no_data(ax, "Direct Trust Score")
    ax.axhline(0.5, color="r", ls=":", lw=0.8, alpha=0.6, label="threshold")
    _add_turn_sections(ax, times, rows)
    _style(ax, "Direct Trust Score", "Trust [0,1]")

    # (0,1) Generalized trust
    ax = fig.add_subplot(gs[0, 1])
    if _plot_series(ax, times, rows, "gtrust", active) == 0:
        _no_data(ax, "Generalized Trust O_i(j)")
    ax.axhline(0.5, color="r", ls=":", lw=0.8, alpha=0.6)
    _add_turn_sections(ax, times, rows)
    _style(ax, "Generalized Trust O_i(j)", "Trust [0,1]")

    # (0,2) Local trust
    ax = fig.add_subplot(gs[0, 2])
    if _plot_series(ax, times, rows, "local_trust", active,
                    label_fmt="LT V{}") == 0:
        _no_data(ax, "Local Trust (gamma_local)")
    _add_turn_sections(ax, times, rows)
    _style(ax, "Local Trust (gamma_local)", "Trust [0,1]")

    # (0,3) Global trust
    ax = fig.add_subplot(gs[0, 3])
    if _plot_series(ax, times, rows, "global_trust", active,
                    label_fmt="GT V{}") == 0:
        _no_data(ax, "Global Trust (gamma_cross)")
    _add_turn_sections(ax, times, rows)
    _style(ax, "Global Trust (gamma_cross)", "Trust [0,1]")

    # (1,0) Trust components for focus vehicle
    ax = fig.add_subplot(gs[1, 0])
    comp = [
        (f"v_score_{focus}", "Velocity"),
        (f"d_score_{focus}", "Distance"),
        (f"a_score_{focus}", "Acceleration"),
        (f"h_score_{focus}", "Heading"),
        (f"b_score_{focus}", "Beacon"),
        (f"q_factor_{focus}", "Quality"),
    ]
    n = 0
    for col, lbl in comp:
        arr = _col_to_array(rows, col)
        if np.any(np.isfinite(arr)):
            ax.plot(times, arr, label=lbl)
            n += 1
    if n == 0:
        _no_data(ax, f"Component Scores (V{focus})")
    _style(ax, f"Component Scores (V{focus})", "Score [0,1]")

    # (1,1) Global trust factors for focus vehicle
    ax = fig.add_subplot(gs[1, 1])
    gamma_cols = [
        (f"gamma_host_{focus}", "gamma_host"),
        (f"gamma_local_peer_{focus}", "gamma_local_peer"),
        (f"gamma_self_{focus}", "gamma_self"),
        (f"global_trust_{focus}", "global_trust"),
    ]
    n = 0
    for col, lbl in gamma_cols:
        arr = _col_to_array(rows, col)
        if np.any(np.isfinite(arr)):
            ax.plot(times, arr, label=lbl)
            n += 1
    if n == 0:
        _no_data(ax, f"Global Trust Factors (V{focus})")
    _style(ax, f"Global Trust Factors (V{focus})", "Value [0,1]")

    # (1,2) Mahalanobis distance terms for focus vehicle
    ax = fig.add_subplot(gs[1, 2])
    dist_cols = [
        (f"d_host_mean_{focus}", "d_host_mean"),
        (f"d_local_mean_{focus}", "d_local_mean"),
        (f"d_self_{focus}", "d_self"),
    ]
    n = 0
    for col, lbl in dist_cols:
        arr = _col_to_array(rows, col)
        if np.any(np.isfinite(arr)):
            ax.plot(times, arr, label=lbl)
            n += 1
    if n == 0:
        _no_data(ax, f"Mahalanobis Distances (V{focus})")
    _style(ax, f"Mahalanobis Distances (V{focus})", "Distance", xlabel="Time [s]")

    # (1,3) Attack flags for focus vehicle
    ax = fig.add_subplot(gs[1, 3])
    flag_cols = [
        (f"flag_attack_{focus}", "Target Attack"),
        (f"flag_local_{focus}", "Local Est Check"),
        (f"flag_global_{focus}", "Global Est Check"),
    ]
    n = 0
    offsets = [0.0, 0.05, 0.10]
    for (col, lbl), off in zip(flag_cols, offsets):
        arr = _col_to_array(rows, col)
        if np.any(np.isfinite(arr)):
            ax.fill_between(times, off, arr + off, alpha=0.5, step="post",
                            label=lbl)
            n += 1
    if n == 0:
        _no_data(ax, f"Attack Flags (V{focus})")
    _style(ax, f"Attack Flags (V{focus})", "Flag", xlabel="Time [s]")

    # (2,0) Relative distance comparison for focus vehicle
    ax = fig.add_subplot(gs[2, 0])
    n = 0
    rel_dist_cols = [
        (f"y_local_distance_{focus}", "Local rel dist"),
        (f"y_true_distance_{focus}", "True rel dist (fallback)"),
        (f"yolo_rel_distance_{focus}", "YOLO rel dist"),
    ]
    for col, lbl in rel_dist_cols:
        arr = _col_to_array(rows, col)
        if np.any(np.isfinite(arr)):
            style = "-" if "YOLO" in lbl else "--"
            ax.plot(times, arr, style, lw=1.3, label=lbl)
            n += 1
    if n == 0:
        _no_data(ax, f"Relative Distance (V{focus})")
    _style(ax, f"Relative Distance (V{focus})", "Distance [m]", xlabel="Time [s]")

    # (2,1) Max Impact Element
    ax = fig.add_subplot(gs[2, 1])
    arr_idx = _col_to_array(rows, f"mi_elem_idx_{focus}")
    arr_val = _col_to_array(rows, f"mi_elem_val_{focus}")
    if np.any(np.isfinite(arr_idx)) and np.any(np.isfinite(arr_val)):
        ax.plot(times, arr_val, label="Max Element Value", color="tab:orange", lw=1.5)
        ax2 = ax.twinx()
        valid_idx = np.isfinite(arr_idx)
        ax2.scatter(np.array(times)[valid_idx], arr_idx[valid_idx], s=10, c="tab:green", alpha=0.5, label="Element Index")
        # use descriptive tick labels instead of raw numbers
        ax2.set_ylabel("Impact Element", fontsize=8)
        ticks = [0, 1, 2, 3, 4]
        labels = ["x", "y", "theta", "v", "a"]
        ax2.set_yticks(ticks)
        ax2.set_yticklabels(labels)
        
        lines1, labels1 = ax.get_legend_handles_labels()
        lines2, labels2 = ax2.get_legend_handles_labels()
        ax.legend(lines1 + lines2, labels1 + labels2, loc="upper right", fontsize=7)
    else:
        _no_data(ax, f"Max Impact Element (V{focus})")
    _style(ax, f"Max Impact Element Index & Score (V{focus})", "Contribution / Score", xlabel="Time [s]", legend=False)

    # (2,2) YOLO-vs-true errors
    ax = fig.add_subplot(gs[2, 2])
    n = 0
    err_cols = [
        (f"yolo_true_rel_dist_error_{focus}", "YOLO-True dist error"),
        (f"yolo_true_rel_vel_error_{focus}", "YOLO-True rel vel error"),
    ]
    for col, lbl in err_cols:
        arr = _col_to_array(rows, col)
        if np.any(np.isfinite(arr)):
            ax.plot(times, arr, lw=1.3, label=lbl)
            n += 1
    if n > 0:
        ax.axhline(0.0, color="k", ls=":", lw=0.8, alpha=0.6)
    if n == 0:
        _no_data(ax, f"YOLO vs True Error (V{focus})")
    _style(ax, f"YOLO vs True Error (V{focus})", "Error", xlabel="Time [s]")

    # (2,3) Relative measurement usage flags
    ax = fig.add_subplot(gs[2, 3])
    n = 0
    flag_cols = [
        (f"rel_meas_used_global_{focus}", "Any external rel used"),
        (f"yolo_rel_meas_used_global_{focus}", "YOLO rel used"),
        (f"rel_dist_meas_used_{focus}", "External dist used"),
        (f"rel_vel_meas_used_{focus}", "External rel vel used"),
    ]
    offsets = [0.00, 0.08, 0.16, 0.24]
    for (col, lbl), off in zip(flag_cols, offsets):
        arr = _col_to_array(rows, col)
        if np.any(np.isfinite(arr)):
            ax.fill_between(times, off, arr + off, alpha=0.5, step="post", label=lbl)
            n += 1
    if n == 0:
        _no_data(ax, f"Relative Measurement Usage (V{focus})")
    _style(ax, f"Relative Measurement Usage (V{focus})", "Flag", xlabel="Time [s]")

    return fig


def _fig_weights(times, rows, active, host_id):
    """
    Figure 2 – Weight Calculation
    Layout (2 rows × 2 cols):
      [0,0] w0, w_self over time             [0,1] Per-neighbor weights
      [1,0] Mean trust metrics                [1,1] Trusted neighbor count
    """
    fig = plt.figure(figsize=(16, 7))
    fig.suptitle(f"Weight Calculation  (Host V{host_id})", fontsize=13,
                 fontweight="bold")
    gs = gridspec.GridSpec(2, 2, figure=fig, hspace=0.35, wspace=0.25)

    # (0,0) w0, w_self
    ax = fig.add_subplot(gs[0, 0])
    n = 0
    for col, lbl, ls in [("w0", "w0 (direct)", "-."),
                          ("w_self", "w_self", "--")]:
        arr = _col_to_array(rows, col)
        if np.any(np.isfinite(arr)):
            ax.plot(times, arr, ls, lw=1.5, label=lbl, color="k" if col == "w_self" else "tab:blue")
            n += 1
    total_arr = _col_to_array(rows, "total_neighbor_weight")
    if np.any(np.isfinite(total_arr)):
        ax.plot(times, total_arr, "-", lw=1.2, label="total_neighbor_w",
                color="tab:orange")
        n += 1
    if n == 0:
        _no_data(ax, "Fixed Weights")
    _style(ax, "Fixed Weights (w0, w_self)", "Weight")

    # (0,1) Per-neighbor weights
    ax = fig.add_subplot(gs[0, 1])
    if _plot_series(ax, times, rows, "w_neighbor", active,
                    label_fmt="w_neighbor V{}") == 0:
        _no_data(ax, "Per-Neighbor Weights")
    _style(ax, "Per-Neighbor Weights", "Weight")

    # (1,0) Mean trust metrics
    ax = fig.add_subplot(gs[1, 0])
    n = 0
    for col, lbl in [("mean_direct_trust", "Mean Direct Trust"),
                      ("mean_generalized_trust", "Mean Generalized Trust"),
                      ("mean_gamma_host", "Mean gamma_host"),
                      ("mean_gamma_local_peer", "Mean gamma_local_peer"),
                      ("mean_gamma_self", "Mean gamma_self"),
                      ("weighted_neighbor_trust", "Weighted Neighbor Trust")]:
        arr = _col_to_array(rows, col)
        if np.any(np.isfinite(arr)):
            ax.plot(times, arr, label=lbl)
            n += 1
    if n == 0:
        _no_data(ax, "Trust Summary Metrics")
    _style(ax, "Trust Summary Metrics", "Value", xlabel="Time [s]")

    # (1,1) Trusted neighbor count
    ax = fig.add_subplot(gs[1, 1])
    n = 0
    for col, lbl in [("trusted_neighbor_count", "Trusted Neighbors"),
                      ("active_vehicle_count", "Active Vehicles")]:
        arr = _col_to_array(rows, col)
        if np.any(np.isfinite(arr)):
            ax.step(times, arr, where="post", label=lbl)
            n += 1
    if n == 0:
        _no_data(ax, "Neighbor Counts")
    _style(ax, "Neighbor / Active Vehicle Counts", "Count",
           xlabel="Time [s]")

    return fig


def _fig_estimation(times, rows, active, host_id):
    """
    Figure 3 – State Estimation
    Layout (4 rows × 2 cols):
      [0,0] Estimated X                      [0,1] Estimated Y
      [1,0] Estimated velocity               [1,1] Estimated acceleration
      [2,0] Estimated heading (theta)        [2,1] Trajectory XY
      [3,0] Estimation confidence + self_belief  [3,1] Prediction mode flags
    """
    fig = plt.figure(figsize=(16, 13))
    fig.suptitle(f"State Estimation  (Host V{host_id})", fontsize=13,
                 fontweight="bold")
    gs = gridspec.GridSpec(4, 2, figure=fig, hspace=0.35, wspace=0.25)

    # (0,0) Estimated X
    ax = fig.add_subplot(gs[0, 0])
    if _plot_series(ax, times, rows, "est_x", active, label_fmt="V{}") == 0:
        _no_data(ax, "Estimated X")
    _style(ax, "Estimated X", "x [m]")

    # (0,1) Estimated Y
    ax = fig.add_subplot(gs[0, 1])
    if _plot_series(ax, times, rows, "est_y", active, label_fmt="V{}") == 0:
        _no_data(ax, "Estimated Y")
    _style(ax, "Estimated Y", "y [m]")

    # (1,0) Velocity
    ax = fig.add_subplot(gs[1, 0])
    if _plot_series(ax, times, rows, "est_v", active, label_fmt="V{}") == 0:
        _no_data(ax, "Estimated Velocity")
    _style(ax, "Estimated Velocity", "v [m/s]")

    # (1,1) Acceleration
    ax = fig.add_subplot(gs[1, 1])
    if _plot_series(ax, times, rows, "est_a", active, label_fmt="V{}") == 0:
        _no_data(ax, "Estimated Acceleration")
    _style(ax, "Estimated Acceleration", "a [m/s²]")

    # (2,0) Estimated Heading (theta)
    ax = fig.add_subplot(gs[2, 0])
    if _plot_series(ax, times, rows, "est_theta", active, label_fmt="V{}") == 0:
        _no_data(ax, "Estimated Heading")
    _style(ax, "Estimated Heading", "theta [rad]")

    # (2,1) Trajectory (XY)
    ax = fig.add_subplot(gs[2, 1])
    n = 0
    for vid in active:
        col_x = f"est_x_{vid}"
        col_y = f"est_y_{vid}"
        arr_x = _col_to_array(rows, col_x)
        arr_y = _col_to_array(rows, col_y)
        if np.any(np.isfinite(arr_x)) and np.any(np.isfinite(arr_y)):
            ax.plot(arr_x, arr_y, label=f"V{vid}")
            # Add a marker at the start
            idx = np.where(np.isfinite(arr_x) & np.isfinite(arr_y))[0]
            if len(idx) > 0:
                ax.plot(arr_x[idx[0]], arr_y[idx[0]], 'o', color=ax.lines[-1].get_color())
            n += 1
    if n == 0:
        _no_data(ax, "Trajectory XY")
    else:
        ax.axis("equal")
    _style(ax, "Trajectory XY", "y [m]", xlabel="x [m]")

    # (3,0) Confidence + self_belief
    ax = fig.add_subplot(gs[3, 0])
    n = _plot_series(ax, times, rows, "est_conf", active,
                     label_fmt="Conf V{}")
    for col, lbl, ls in [("self_belief", "self_belief", "--"),
                          ("platoon_conf_mean", "platoon_conf_mean", "-"),
                          ("platoon_conf_min", "platoon_conf_min", ":"),
                          ("platoon_conf_max", "platoon_conf_max", ":")]:
        arr = _col_to_array(rows, col)
        if np.any(np.isfinite(arr)):
            ax.plot(times, arr, ls, lw=1.3, label=lbl, color="k")
            n += 1
    if n == 0:
        _no_data(ax, "Estimation Confidence")
    _style(ax, "Estimation Confidence", "Confidence", xlabel="Time [s]")

    # (3,1) Prediction mode flags
    ax = fig.add_subplot(gs[3, 1])
    n = 0
    for vid in active:
        col = f"pred_mode_{vid}"
        arr = _col_to_array(rows, col)
        if np.any(np.isfinite(arr)):
            ax.step(times, arr, where="post", label=f"V{vid}")
            n += 1
    pred_count = _col_to_array(rows, "prediction_mode_count")
    if np.any(np.isfinite(pred_count)):
        ax.plot(times, pred_count, "k--", lw=1.3, label="total_pred_mode")
        n += 1
    if n == 0:
        _no_data(ax, "Prediction Mode")
    _style(ax, "Prediction Mode Flags", "Mode (0/1)", xlabel="Time [s]")

    return fig


def _fig_relative_uio(filepath: str, host_id: int):
    """
    Figure 6 - Relative UIO diagnostics from relative_uio_log_V*.csv.
    """
    columns, rows = _load_csv(filepath)
    if "time" not in columns or not rows:
        print(f"Relative UIO log has no plottable samples: {filepath}")
        return None

    times = _col_to_array(rows, "time")
    target_ids = _col_to_array(rows, "target_id")
    finite_targets = target_ids[np.isfinite(target_ids)]
    target_label = (
        f"V{int(finite_targets[-1])}" if finite_targets.size > 0 else "unknown target"
    )

    fig = plt.figure(figsize=(18, 18))
    fig.suptitle(
        f"Relative UIO Diagnostics  (Host V{host_id}, Target {target_label})",
        fontsize=13,
        fontweight="bold",
    )
    gs = gridspec.GridSpec(5, 2, figure=fig, hspace=0.35, wspace=0.25)

    # Kinematic state estimates
    ax = fig.add_subplot(gs[0, 0])
    n = 0
    for col, label in [
        ("delta_hat", "delta_hat"),
        ("delta_dot_hat", "delta_dot_hat"),
        ("delta_ddot_hat", "delta_ddot_hat"),
    ]:
        arr = _col_to_array(rows, col)
        if np.any(np.isfinite(arr)):
            ax.plot(times, arr, label=label)
            n += 1
    if n == 0:
        _no_data(ax, "UIO Kinematic State Estimates")
    _style(ax, "UIO Kinematic State Estimates", "Estimate")

    # Distance estimate against measurements and V2V fallback
    ax = fig.add_subplot(gs[0, 1])
    n = 0
    for col, label, style in [
        ("delta_hat", "UIO distance estimate", "-"),
        ("measurement_distance", "Measured distance", "--"),
        ("v2v_fallback_distance", "V2V-derived distance", ":"),
    ]:
        arr = _col_to_array(rows, col)
        if np.any(np.isfinite(arr)):
            ax.plot(times, arr, style, label=label)
            n += 1
    if n == 0:
        _no_data(ax, "Relative Distance")
    _style(ax, "Relative Distance", "Distance [m]")

    # Relative velocity estimate against measurements and V2V fallback
    ax = fig.add_subplot(gs[1, 0])
    n = 0
    for col, label, style in [
        ("delta_dot_hat", "UIO relative velocity", "-"),
        ("measurement_relative_velocity", "Measured relative velocity", "--"),
        ("v2v_fallback_relative_velocity", "V2V-derived relative velocity", ":"),
    ]:
        arr = _col_to_array(rows, col)
        if np.any(np.isfinite(arr)):
            ax.plot(times, arr, style, label=label)
            n += 1
    if n == 0:
        _no_data(ax, "Relative Velocity")
    _style(ax, "Relative Velocity", "Velocity [m/s]")

    # Relative acceleration estimate against V2V-derived acceleration
    ax = fig.add_subplot(gs[1, 1])
    rel_acc_v2v = _col_to_array(rows, "v2v_fallback_relative_acceleration")
    if not np.any(np.isfinite(rel_acc_v2v)):
        target_acc = _col_to_array(rows, "target_state_4")
        host_acc = _col_to_array(rows, "host_state_4")
        if np.any(np.isfinite(target_acc)) and np.any(np.isfinite(host_acc)):
            rel_acc_v2v = target_acc - host_acc

    n = 0
    for arr, label, style in [
        (_col_to_array(rows, "delta_ddot_hat"), "UIO relative acceleration delta_ddot_hat", "-"),
        (rel_acc_v2v, "V2V-derived relative acceleration", ":"),
        (_col_to_array(rows, "target_acceleration_input"), "Target acceleration input", "--"),
    ]:
        if np.any(np.isfinite(arr)):
            ax.plot(times, arr, style, label=label)
            n += 1
    if n > 0:
        ax.axhline(0.0, color="k", ls=":", lw=0.8, alpha=0.6)
    if n == 0:
        _no_data(ax, "Relative Acceleration")
    _style(ax, "Relative Acceleration Estimate", "Acceleration [m/s^2]")

    # Measurement / estimate errors against V2V-derived fallback
    ax = fig.add_subplot(gs[2, 0])
    n = 0
    rel_acc_error = _col_to_array(rows, "relative_acceleration_error_vs_v2v")
    if not np.any(np.isfinite(rel_acc_error)):
        delta_ddot = _col_to_array(rows, "delta_ddot_hat")
        if np.any(np.isfinite(delta_ddot)) and np.any(np.isfinite(rel_acc_v2v)):
            rel_acc_error = delta_ddot - rel_acc_v2v

    for arr, label in [
        (_col_to_array(rows, "distance_error_vs_v2v"), "Distance error"),
        (_col_to_array(rows, "relative_velocity_error_vs_v2v"), "Relative velocity error"),
        (rel_acc_error, "Relative acceleration error"),
    ]:
        if np.any(np.isfinite(arr)):
            ax.plot(times, arr, label=label)
            n += 1
    if n > 0:
        ax.axhline(0.0, color="k", ls=":", lw=0.8, alpha=0.6)
    if n == 0:
        _no_data(ax, "Measurement Error vs V2V")
    _style(ax, "Measurement Error vs V2V", "Error", xlabel="Time [s]")

    # Measurement availability/quality
    ax = fig.add_subplot(gs[2, 1])
    n = 0
    for col, label, style in [
        ("measurement_used", "Measurement used", "-"),
        ("measurement_confidence", "Measurement confidence", "--"),
        ("measurement_age_s", "Measurement age [s]", ":"),
    ]:
        arr = _col_to_array(rows, col)
        if np.any(np.isfinite(arr)):
            ax.plot(times, arr, style, label=label)
            n += 1
    if n == 0:
        _no_data(ax, "Measurement Usage")
    _style(ax, "Measurement Usage / Quality", "Value", xlabel="Time [s]")

    # Inputs used by the observer
    ax = fig.add_subplot(gs[3, 0])
    n = 0
    for col, label in [
        ("host_velocity_input", "Host velocity input"),
        ("target_acceleration_input", "Target acceleration input"),
    ]:
        arr = _col_to_array(rows, col)
        if np.any(np.isfinite(arr)):
            ax.plot(times, arr, label=label)
            n += 1
    if n == 0:
        _no_data(ax, "UIO Inputs")
    _style(ax, "UIO Inputs", "Input", xlabel="Time [s]")

    # Unknown input / cyber-disturbance estimate separated from kinematics
    ax = fig.add_subplot(gs[3:5, 1])
    arr = _col_to_array(rows, "f_c_hat")
    if np.any(np.isfinite(arr)):
        ax.plot(times, arr, label="d_c_hat / f_c_hat", color="tab:red", lw=1.4)
        ax.axhline(0.0, color="k", ls=":", lw=0.8, alpha=0.6)
    else:
        _no_data(ax, "Unknown Input Estimate")
    _style(ax, "Unknown Input Estimate d_c_hat / f_c_hat", "Estimate", xlabel="Time [s]")

    return fig


def _fig_impact_histograms(rows, active, focus, host_id):
    """
    Figure 4 - Impact Overview Histograms
    Layout (1 row x 2 cols):
      [0,0] Max Impact Vehicle Frequency  [0,1] Max Impact Element Frequency
    """
    fig = plt.figure(figsize=(12, 5))
    fig.suptitle(f"Max Impact Overview (Host V{host_id}, Focus V{focus})", fontsize=13, fontweight="bold")
    gs = gridspec.GridSpec(1, 2, figure=fig, wspace=0.3)
    
    # [0,0] Max Impact Vehicle
    ax1 = fig.add_subplot(gs[0, 0])
    veh_col = _col_to_array(rows, f"mi_veh_id_{focus}")
    if np.any(np.isfinite(veh_col)):
        valid_vehs = veh_col[np.isfinite(veh_col)].astype(int)
        unique_vehs, counts = np.unique(valid_vehs, return_counts=True)
        ax1.bar([f"V{v}" for v in unique_vehs], counts, color="tab:blue", alpha=0.7)
        for i, count in enumerate(counts):
            ax1.text(i, count, str(count), ha="center", va="bottom", fontsize=9)
        ax1.set_ylabel("Frequency")
        ax1.set_title(f"Max Impact Vehicle Frequency (Focus V{focus})")
    else:
        _no_data(ax1, f"Max Impact Vehicle (V{focus})")
        
    # [0,1] Max Impact Element Index
    ax2 = fig.add_subplot(gs[0, 1])
    idx_col = _col_to_array(rows, f"mi_elem_idx_{focus}")
    if np.any(np.isfinite(idx_col)):
        valid_idxs = idx_col[np.isfinite(idx_col)].astype(int)
        unique_idxs, counts = np.unique(valid_idxs, return_counts=True)
        elem_names = {0: "x", 1: "y", 2: "theta", 3: "v", 4: "a"}
        labels = [elem_names.get(i, str(i)) for i in unique_idxs]
        ax2.bar(labels, counts, color="tab:orange", alpha=0.7)
        for i, count in enumerate(counts):
            ax2.text(i, count, str(count), ha="center", va="bottom", fontsize=9)
        ax2.set_ylabel("Frequency")
        ax2.set_title(f"Max Impact Element Frequency (Focus V{focus})")
    else:
        _no_data(ax2, f"Max Impact Element (V{focus})")

    fig.tight_layout(rect=[0, 0, 1, 0.95])
    return fig


def _fig_v2v_details(times, rows, active, focus, host_id):
    """
    Figure 5 - Detailed V2V Tracking for Global Trust
    Layout (2 rows x 2 cols):
      [0,0] Distance per evaluated vehicle    [0,1] Element Value per evaluated vehicle
      [1,0:2] Element Index per evaluated vehicle (Scatter)
    """
    fig = plt.figure(figsize=(14, 9))
    fig.suptitle(f"V2V Detailed Tracking (Host V{host_id} evaluating Focus V{focus})", fontsize=13, fontweight="bold")
    gs = gridspec.GridSpec(2, 2, figure=fig, hspace=0.35, wspace=0.25)

    # Find the k indices that have data
    available_k = []
    # Test up to 20 just in case
    for k in range(20):
        if _col_to_array(rows, f"g_dist_v{k}_{focus}").any():
            available_k.append(k)

    if not available_k:
        # Fallback if no detailed data
        ax = fig.add_subplot(gs[0, 0])
        _no_data(ax, "V2V Distance Tracking")
        return fig

    elem_markers = {0: 's', 1: 'D', 2: '^', 3: 'v', 4: 'o'}
    elem_names = {0: "x", 1: "y", 2: "theta", 3: "v", 4: "a"}

    # [0,0] Distances
    ax = fig.add_subplot(gs[0, 0])
    
    # Add dummy legend entries for marker shapes
    for idx, m in elem_markers.items():
        ax.plot([], [], color='gray', marker=m, linestyle='None', label=f"Impact: {elem_names[idx]}")

    n = 0
    for k in available_k:
        col_dist = f"g_dist_v{k}_{focus}"
        col_idx = f"g_idx_v{k}_{focus}"
        arr_dist = _col_to_array(rows, col_dist)
        arr_idx = _col_to_array(rows, col_idx)

        if np.any(np.isfinite(arr_dist)):
            p = ax.plot(times, arr_dist, label=f"V{k}")
            color = p[0].get_color()
            
            # Overlay markers indicating max impact element
            valid_mask = np.isfinite(arr_dist) & np.isfinite(arr_idx)
            if np.any(valid_mask):
                t_valid = np.array(times)[valid_mask]
                d_valid = arr_dist[valid_mask]
                i_valid = arr_idx[valid_mask].astype(int)
                
                for idx in np.unique(i_valid):
                    idx_mask = (i_valid == idx)
                    ax.scatter(t_valid[idx_mask], d_valid[idx_mask], color=color, marker=elem_markers.get(idx, 'o'), s=30, alpha=0.7, zorder=3)
            n += 1

    if n == 0:
        _no_data(ax, "V2V Distance")
    _style(ax, "Mahalanobis Distance per Vehicle", "Distance", xlabel="Time [s]")

    # [0,1] Element Values
    ax = fig.add_subplot(gs[0, 1])
    # Add dummy legend entries for marker shapes
    for idx, m in elem_markers.items():
        ax.plot([], [], color='gray', marker=m, linestyle='None', label=f"Impact: {elem_names[idx]}")

    n = 0
    for k in available_k:
        col_val = f"g_val_v{k}_{focus}"
        col_idx = f"g_idx_v{k}_{focus}"
        arr_val = _col_to_array(rows, col_val)
        arr_idx = _col_to_array(rows, col_idx)

        if np.any(np.isfinite(arr_val)):
            p = ax.plot(times, arr_val, label=f"V{k}")
            color = p[0].get_color()
            
            # Overlay markers indicating max impact element
            valid_mask = np.isfinite(arr_val) & np.isfinite(arr_idx)
            if np.any(valid_mask):
                t_valid = np.array(times)[valid_mask]
                v_valid = arr_val[valid_mask]
                i_valid = arr_idx[valid_mask].astype(int)
                
                for idx in np.unique(i_valid):
                    idx_mask = (i_valid == idx)
                    ax.scatter(t_valid[idx_mask], v_valid[idx_mask], color=color, marker=elem_markers.get(idx, 'o'), s=30, alpha=0.7, zorder=3)
            n += 1

    if n == 0:
        _no_data(ax, "V2V Element Value")
    _style(ax, "Max Impact Element Value per Vehicle", "Value", xlabel="Time [s]")

    # [1,0:2] Element Indices
    ax = fig.add_subplot(gs[1, 0:2])
    n = 0
    for k in available_k:
        col = f"g_idx_v{k}_{focus}"
        arr = _col_to_array(rows, col)
        if np.any(np.isfinite(arr)):
            valid_mask = np.isfinite(arr)
            ax.scatter(np.array(times)[valid_mask], arr[valid_mask], s=15, alpha=0.6, label=f"V{k}")
            n += 1

    if n == 0:
        _no_data(ax, "V2V Element Index")
    else:
        ax.set_yticks([0, 1, 2, 3, 4])
        ax.set_yticklabels(["x", "y", "theta", "v", "a"])
    _style(ax, "Max Impact Element Index per Vehicle", "Element", xlabel="Time [s]")

    return fig


def _print_static_metrics(rows, active):
    """
    Print an analytic summary of the trust logging run to the console.
    Helps tune parameters by surfacing the most common threshold breakers.
    """
    print("\n" + "="*80)
    print(f"{'STATIC METRICS DASHBOARD':^80}")
    print("="*80)
    
    elem_names = {0: "x", 1: "y", 2: "theta", 3: "v", 4: "a"}

    print(f"{'Vehicle':<10} | {'Target Atk':<12} | {'Local Est Bad':<15} | {'Global Est Bad':<16} | {'Max Impact Elements (Count)'}")
    print("-" * 80)

    for vid in active:
        # Tally attack flags
        target_atk_col = _col_to_array(rows, f"flag_attack_{vid}")
        local_est_col = _col_to_array(rows, f"flag_local_{vid}")
        global_est_col = _col_to_array(rows, f"flag_global_{vid}")
        
        target_atks = int(np.nansum(target_atk_col)) if np.any(np.isfinite(target_atk_col)) else 0
        local_bads = int(np.nansum(local_est_col)) if np.any(np.isfinite(local_est_col)) else 0
        global_bads = int(np.nansum(global_est_col)) if np.any(np.isfinite(global_est_col)) else 0
        
        # Determine element offenders
        elem_idx_col = _col_to_array(rows, f"mi_elem_idx_{vid}")
        dist_col = _col_to_array(rows, f"mi_dist_{vid}")
        
        elem_str = "None"
        if np.any(np.isfinite(elem_idx_col)):
            valid_idx = np.isfinite(elem_idx_col)
            valid_elems = elem_idx_col[valid_idx].astype(int)
            valid_dists = dist_col[valid_idx] if np.any(np.isfinite(dist_col)) else np.zeros_like(valid_elems)
            
            # Count the occurrences of each element being the max impact
            counts = {i: 0 for i in range(5)}
            dist_sums = {i: 0.0 for i in range(5)}
            
            for e, d in zip(valid_elems, valid_dists):
                if e in counts:
                    counts[e] += 1
                    dist_sums[e] += d
                    
            # Sort by count descending
            sorted_elems = sorted(counts.items(), key=lambda x: x[1], reverse=True)
            
            elem_strs = []
            for e, count in sorted_elems:
                if count > 0:
                    avg_d = dist_sums[e] / count
                    name = elem_names.get(e, str(e))
                    elem_strs.append(f"{name} ({count}x, avg dist: {avg_d:.2f})")
            
            if elem_strs:
                elem_str = ", ".join(elem_strs[:2]) # Show top 2
        
        print(f"V{vid:<9} | {target_atks:<12} | {local_bads:<15} | {global_bads:<16} | {elem_str}")

    print("="*80 + "\n")


def _relative_time_axis(times: np.ndarray) -> np.ndarray:
    """Return a monotonic relative-time axis suitable for playback."""
    n = len(times)
    if n == 0:
        return np.array([], dtype=float)

    raw = np.asarray(times, dtype=float)
    finite = np.isfinite(raw)
    if np.count_nonzero(finite) < 2:
        return np.arange(n, dtype=float)

    sample_index = np.arange(n, dtype=float)
    filled = raw.copy()
    filled[~finite] = np.interp(sample_index[~finite],
                                sample_index[finite], raw[finite])

    diffs = np.diff(filled)
    positive_diffs = diffs[np.isfinite(diffs) & (diffs > 0.0)]
    median_dt = float(np.median(positive_diffs)) if positive_diffs.size else 1.0
    if median_dt <= 0.0 or not math.isfinite(median_dt):
        median_dt = 1.0

    if np.any(diffs < -1e-9):
        filled = sample_index * median_dt
    else:
        filled = np.maximum.accumulate(filled)

    return filled - filled[0]


def _finite_limits(arrays, default=(0.0, 1.0), pad_fraction=0.08):
    vals = []
    for arr in arrays:
        if arr is None:
            continue
        arr = np.asarray(arr, dtype=float).ravel()
        vals.append(arr[np.isfinite(arr)])
    vals = [v for v in vals if v.size]
    if not vals:
        return default

    joined = np.concatenate(vals)
    ymin = float(np.min(joined))
    ymax = float(np.max(joined))
    if math.isclose(ymin, ymax):
        pad = max(abs(ymin) * pad_fraction, 0.1)
    else:
        pad = (ymax - ymin) * pad_fraction
    return ymin - pad, ymax + pad


def _set_axis_y_limits(ax, arrays, bounded_unit=False):
    if bounded_unit:
        ax.set_ylim(-0.05, 1.05)
    else:
        ax.set_ylim(*_finite_limits(arrays))


def _format_live_value(value) -> str:
    try:
        value = float(value)
    except (TypeError, ValueError):
        return "nan"
    if not math.isfinite(value):
        return "nan"
    return f"{value:.3f}"


def _run_playback_dashboard(file_to_plot: str, times: np.ndarray,
                            rows: List[dict], columns: List[str],
                            active: List[int], focus: int, host_id: int,
                            speed: float = 1.0, window_s: float = 30.0,
                            interval_ms: int = 50,
                            start_time: float = None,
                            loop: bool = True,
                            max_points: int = 1200):
    """
    Replays a trust log as a live dashboard.

    Keyboard controls:
      Space: pause/resume
      Left/Right: seek 5 seconds
      Home/End: jump to start/end
      +/-: change playback speed
    """
    if len(rows) == 0:
        print("No rows to play back.")
        return None

    speed = max(float(speed), 1e-6)
    interval_ms = max(int(interval_ms), 10)
    window_s = float(window_s)
    max_points = max(int(max_points), 0)

    t_rel = _relative_time_axis(times)
    if t_rel.size == 0:
        print("No valid time samples to play back.")
        return None

    duration = float(t_rel[-1])
    if start_time is None:
        start_t = 0.0
    else:
        start_t = min(max(float(start_time), 0.0), duration)

    def arr(col):
        return _col_to_array(rows, col) if col in columns else np.full(len(rows), np.nan)

    arrays = {}
    base_cols = [
        "w0", "w_self", "total_neighbor_weight", "trusted_neighbor_count",
        "active_vehicle_count", "is_turning", "v2v_attack_active",
        "v2v_attack_active_count",
    ]
    for col in base_cols:
        arrays[col] = arr(col)

    per_vehicle_prefixes = [
        "trust", "gtrust", "local_trust", "global_trust",
        "w_neighbor", "pred_mode", "est_x", "est_y",
        "v_score", "d_score", "a_score", "h_score", "b_score",
        "q_factor", "gamma_host", "gamma_local_peer", "gamma_self",
        "flag_attack", "flag_local", "flag_global",
        "rel_meas_used_global", "yolo_rel_meas_used_global",
    ]
    for vid in active:
        for prefix in per_vehicle_prefixes:
            col = f"{prefix}_{vid}"
            arrays[col] = arr(col)

    fig = plt.figure(figsize=(18, 10.5))
    fig.suptitle(
        f"Realtime Trust Log Playback - {os.path.basename(file_to_plot)} "
        f"(Host V{host_id}, Focus V{focus})",
        fontsize=14,
        fontweight="bold",
    )
    gs = gridspec.GridSpec(
        3, 3, figure=fig, hspace=0.42, wspace=0.30,
        height_ratios=[1.0, 1.0, 0.78],
    )

    ax_trust = fig.add_subplot(gs[0, 0])
    ax_weights = fig.add_subplot(gs[0, 1])
    ax_components = fig.add_subplot(gs[0, 2])
    ax_gamma = fig.add_subplot(gs[1, 0])
    ax_final = fig.add_subplot(gs[1, 1])
    ax_xy = fig.add_subplot(gs[1, 2])
    ax_flags = fig.add_subplot(gs[2, 0:2])
    ax_status = fig.add_subplot(gs[2, 2])
    ax_status.axis("off")

    time_lines = []
    xy_lines = []
    colors = plt.rcParams["axes.prop_cycle"].by_key().get("color", [])
    if not colors:
        colors = ["C0", "C1", "C2", "C3", "C4", "C5"]

    def add_time_line(ax, col, label, *, color=None, ls="-", lw=1.4,
                      alpha=1.0, drawstyle="default", marker=None):
        data = arrays.get(col)
        if data is None or not np.any(np.isfinite(data)):
            return None
        line, = ax.plot([], [], label=label, color=color, ls=ls, lw=lw,
                        alpha=alpha, drawstyle=drawstyle, marker=marker,
                        markersize=3)
        time_lines.append((line, data))
        return line

    # Trust scores for all active vehicles.
    for i, vid in enumerate(active):
        color = colors[i % len(colors)]
        add_time_line(ax_trust, f"trust_{vid}", f"trust V{vid}",
                      color=color, lw=1.5)
        add_time_line(ax_trust, f"gtrust_{vid}", f"gtrust V{vid}",
                      color=color, ls="--", alpha=0.75, lw=1.2)
    ax_trust.axhline(0.5, color="r", ls=":", lw=0.9, alpha=0.7)
    _style(ax_trust, "Direct and Generalized Trust", "Trust [0,1]",
           legend=True)
    _set_axis_y_limits(ax_trust,
                       [arrays.get(f"trust_{v}") for v in active] +
                       [arrays.get(f"gtrust_{v}") for v in active],
                       bounded_unit=True)

    # Weights.
    add_time_line(ax_weights, "w0", "w0", color="k", ls="-.")
    add_time_line(ax_weights, "w_self", "w_self", color="tab:blue", ls="--")
    add_time_line(ax_weights, "total_neighbor_weight", "neighbor total",
                  color="tab:orange")
    for i, vid in enumerate(active):
        add_time_line(ax_weights, f"w_neighbor_{vid}", f"w V{vid}",
                      color=colors[i % len(colors)], alpha=0.8, lw=1.1)
    _style(ax_weights, "Consensus Weights", "Weight", legend=True)
    _set_axis_y_limits(
        ax_weights,
        [arrays.get("w0"), arrays.get("w_self"),
         arrays.get("total_neighbor_weight")] +
        [arrays.get(f"w_neighbor_{v}") for v in active],
    )

    # Focus trust components.
    component_cols = [
        (f"v_score_{focus}", "velocity"),
        (f"d_score_{focus}", "distance"),
        (f"a_score_{focus}", "acceleration"),
        (f"h_score_{focus}", "heading"),
        (f"b_score_{focus}", "beacon"),
        (f"q_factor_{focus}", "quality"),
    ]
    for i, (col, label) in enumerate(component_cols):
        add_time_line(ax_components, col, label, color=colors[i % len(colors)])
    _style(ax_components, f"Component Scores Local Trust V{focus}", "Score [0,1]",
           legend=True)
    _set_axis_y_limits(ax_components,
                       [arrays.get(col) for col, _ in component_cols],
                       bounded_unit=True)

    # Focus global trust factors.
    gamma_cols = [
        (f"gamma_host_{focus}", "gamma_host"),
        (f"gamma_local_peer_{focus}", "gamma_local_peer"),
        (f"gamma_self_{focus}", "gamma_self"),
    ]
    for i, (col, label) in enumerate(gamma_cols):
        add_time_line(ax_gamma, col, label, color=colors[i % len(colors)])
    _style(ax_gamma, f"Component Scores Global Trust V{focus}", "Value [0,1]",
           legend=True)
    _set_axis_y_limits(ax_gamma, [arrays.get(col) for col, _ in gamma_cols],
                       bounded_unit=True)

    # Final local/global trust scores for the focus vehicle.
    final_cols = [
        (f"local_trust_{focus}", "local trust", "-"),
        (f"global_trust_{focus}", "global trust", "--"),
    ]
    for i, (col, label, ls) in enumerate(final_cols):
        add_time_line(ax_final, col, label, color=colors[i % len(colors)], ls=ls)
    _style(ax_final, f"Final Trust Score Local and Global V{focus}",
           "Trust [0,1]", legend=True)
    _set_axis_y_limits(ax_final, [arrays.get(col) for col, _, _ in final_cols],
                       bounded_unit=True)

    # Estimated XY trajectories.
    for i, vid in enumerate(active):
        x = arrays.get(f"est_x_{vid}")
        y = arrays.get(f"est_y_{vid}")
        if x is None or y is None or not (np.any(np.isfinite(x)) and np.any(np.isfinite(y))):
            continue
        color = colors[i % len(colors)]
        traj_line, = ax_xy.plot([], [], label=f"V{vid}", color=color, lw=1.4)
        marker_line, = ax_xy.plot([], [], marker="o", color=color,
                                  linestyle="None", markersize=5)
        xy_lines.append((traj_line, marker_line, x, y))
    _style(ax_xy, "Estimated XY Trajectory", "Y [m]", xlabel="X [m]",
           legend=True)
    all_x = [arrays.get(f"est_x_{v}") for v in active]
    all_y = [arrays.get(f"est_y_{v}") for v in active]
    ax_xy.set_xlim(*_finite_limits(all_x, default=(-1.0, 1.0)))
    ax_xy.set_ylim(*_finite_limits(all_y, default=(-1.0, 1.0)))
    ax_xy.set_aspect("auto")

    # Flags and activity.
    flag_cols = [
        (f"flag_attack_{focus}", "target attack", 0.0),
        (f"flag_local_{focus}", "local bad", 0.15),
        (f"flag_global_{focus}", "global bad", 0.30),
        (f"rel_meas_used_global_{focus}", "rel used", 0.45),
        (f"yolo_rel_meas_used_global_{focus}", "YOLO used", 0.60),
        (f"pred_mode_{focus}", "prediction", 0.75),
        ("is_turning", "turning", 0.90),
        ("v2v_attack_active", "V2V attack", 1.05),
    ]
    for i, (col, label, offset) in enumerate(flag_cols):
        data = arrays.get(col)
        if data is None or not np.any(np.isfinite(data)):
            continue
        shifted = np.where(np.isfinite(data), data, 0.0) * 0.10 + offset
        arrays[f"__flag_{col}"] = shifted
        add_time_line(ax_flags, f"__flag_{col}", label,
                      color=colors[i % len(colors)], lw=1.5,
                      drawstyle="steps-post")
    ax_flags.set_ylim(-0.05, 1.20)
    ax_flags.set_yticks([item[2] + 0.05 for item in flag_cols])
    ax_flags.set_yticklabels([item[1] for item in flag_cols], fontsize=8)
    _style(ax_flags, f"Flags V{focus}", "", xlabel="Time [s]", legend=False)

    ax_status.set_title("Playback Status", fontsize=10, fontweight="bold")
    status_left_text = ax_status.text(
        0.02, 0.92, "", va="top", ha="left",
        family="monospace", fontsize=9.5, transform=ax_status.transAxes,
    )
    status_right_text = ax_status.text(
        0.54, 0.92, "", va="top", ha="left",
        family="monospace", fontsize=9.5, transform=ax_status.transAxes,
    )
    ax_status.text(
        0.02, 0.02,
        "Space pause | Left/Right seek | Home/End jump | +/- speed",
        va="bottom",
        ha="left",
        fontsize=8.5,
        color="#555",
        transform=ax_status.transAxes,
    )

    time_axes = [
        ax_trust, ax_weights, ax_components, ax_gamma,
        ax_final, ax_flags,
    ]
    for ax in time_axes:
        ax.set_xlim(0.0, max(1.0, min(duration, window_s if window_s > 0 else duration)))

    state = {
        "paused": False,
        "wall_start": time.perf_counter(),
        "sim_start": start_t,
        "current_t": start_t,
        "speed": speed,
    }

    def seek(target_t):
        target_t = min(max(float(target_t), 0.0), duration)
        state["current_t"] = target_t
        state["sim_start"] = target_t
        state["wall_start"] = time.perf_counter()
        update_frame(target_t)
        fig.canvas.draw_idle()

    def update_frame(current_t):
        idx = int(np.searchsorted(t_rel, current_t, side="right") - 1)
        idx = max(0, min(idx, len(rows) - 1))

        if window_s > 0:
            left_t = max(0.0, current_t - window_s)
            right_t = max(window_s, current_t)
            right_t = min(max(right_t, 1.0), max(duration, 1.0))
        else:
            left_t = 0.0
            right_t = max(duration, 1.0)

        start_idx = int(np.searchsorted(t_rel, left_t, side="left"))
        end_idx = idx + 1
        visible_count = max(end_idx - start_idx, 1)
        point_step = 1
        if max_points > 0 and visible_count > max_points:
            point_step = int(math.ceil(visible_count / max_points))
        plot_slice = slice(start_idx, end_idx, point_step)
        x_time = t_rel[plot_slice]

        for line, data in time_lines:
            line.set_data(x_time, data[plot_slice])

        for traj_line, marker_line, x, y in xy_lines:
            traj_line.set_data(x[plot_slice], y[plot_slice])
            if np.isfinite(x[idx]) and np.isfinite(y[idx]):
                marker_line.set_data([x[idx]], [y[idx]])
            else:
                marker_line.set_data([], [])

        for ax in time_axes:
            ax.set_xlim(left_t, right_t)

        left_lines = [
            f"time    {t_rel[idx]:7.2f} / {duration:7.2f}s",
            f"sample  {idx + 1:7d} / {len(rows):7d}",
            f"speed   {state['speed']:7.2f}x",
            f"state   {'PAUSED' if state['paused'] else 'PLAYING'}",
            f"window  {max(window_s, 0.0):7.2f}s",
        ]
        right_lines = [
            f"focus V{focus}",
            f"local  {_format_live_value(arrays.get(f'local_trust_{focus}', [np.nan])[idx])}",
            f"global {_format_live_value(arrays.get(f'global_trust_{focus}', [np.nan])[idx])}",
            f"direct {_format_live_value(arrays.get(f'trust_{focus}', [np.nan])[idx])}",
            f"weight {_format_live_value(arrays.get(f'w_neighbor_{focus}', [np.nan])[idx])}",
            f"active {int(arrays['active_vehicle_count'][idx]) if np.isfinite(arrays['active_vehicle_count'][idx]) else 0}",
            f"trusted {int(arrays['trusted_neighbor_count'][idx]) if np.isfinite(arrays['trusted_neighbor_count'][idx]) else 0}",
        ]
        status_left_text.set_text("\n".join(left_lines))
        status_right_text.set_text("\n".join(right_lines))

    def on_timer():
        if state["paused"]:
            return True

        elapsed = time.perf_counter() - state["wall_start"]
        current_t = state["sim_start"] + elapsed * state["speed"]
        if current_t >= duration:
            if loop and duration > 0.0:
                current_t = 0.0
                state["sim_start"] = 0.0
                state["wall_start"] = time.perf_counter()
            else:
                current_t = duration
                state["paused"] = True

        state["current_t"] = current_t
        update_frame(current_t)
        fig.canvas.draw_idle()
        return True

    def on_key(event):
        if event.key in (" ", "space"):
            state["paused"] = not state["paused"]
            state["sim_start"] = state["current_t"]
            state["wall_start"] = time.perf_counter()
            update_frame(state["current_t"])
            fig.canvas.draw_idle()
        elif event.key == "right":
            seek(state["current_t"] + 5.0)
        elif event.key == "left":
            seek(state["current_t"] - 5.0)
        elif event.key == "home":
            seek(0.0)
        elif event.key == "end":
            seek(duration)
        elif event.key in ("+", "="):
            state["speed"] = min(state["speed"] * 1.25, 100.0)
            state["sim_start"] = state["current_t"]
            state["wall_start"] = time.perf_counter()
        elif event.key in ("-", "_"):
            state["speed"] = max(state["speed"] / 1.25, 0.01)
            state["sim_start"] = state["current_t"]
            state["wall_start"] = time.perf_counter()

    fig.canvas.mpl_connect("key_press_event", on_key)
    update_frame(start_t)

    timer = fig.canvas.new_timer(interval=interval_ms)
    timer.add_callback(on_timer)
    timer.start()
    fig._trust_playback_timer = timer

    return fig


def main():
    parser = argparse.ArgumentParser(
        description="Plot trust/weight logs."
    )
    parser.add_argument("--file", "-f", help="path to a specific CSV file to plot")
    parser.add_argument("--all", action="store_true",
                        help="generate figures for every candidate focus vehicle")
    parser.add_argument("--focus", type=int,
                        help="vehicle ID to use as focus (overrides interactive choice)")
    parser.add_argument("--relative-file",
                        help="path to a relative_uio_log_V*.csv file to plot")
    parser.add_argument("--skip-relative", action="store_true",
                        help="do not auto-load matching relative UIO log")
    parser.add_argument("--playback", action="store_true",
                        help="replay the selected CSV as a realtime dashboard")
    parser.add_argument("--speed", type=float, default=1.0,
                        help="playback speed multiplier for --playback (default: 1.0)")
    parser.add_argument("--window", type=float, default=30.0,
                        help="scrolling time window in seconds for --playback; use 0 for full history")
    parser.add_argument("--playback-interval", type=int, default=30ack,
                        help="dashboard refresh interval in milliseconds for --playback")
    parser.add_argument("--max-points", type=int, default=1200,
                        help="maximum visible points per line during playback; use 0 to disable downsampling")
    parser.add_argument("--start-time", type=float,
                        help="start playback at this elapsed log time in seconds")
    parser.add_argument("--no-loop", action="store_true",
                        help="stop at the end of playback instead of looping")
    args = parser.parse_args()

    directory = os.path.dirname(os.path.abspath(__file__))
    csv_files = sorted(glob.glob(os.path.join(directory,
                                              "trust_weight_log_V*.csv")))
    if not csv_files:
        print("No trust log files found in:", directory)
        return

    if args.file:
        file_to_plot = args.file
        if not os.path.isfile(file_to_plot):
            print(f"Specified file does not exist: {file_to_plot}")
            return
    else:
        print("Found files:")
        for i, f in enumerate(csv_files):
            print(f"[{i}] {os.path.basename(f)}")

        choice = input(f"Select file to plot [0-{len(csv_files) - 1}]: ").strip()
        try:
            choice = int(choice)
            file_to_plot = csv_files[choice]
        except (ValueError, IndexError):
            print("Invalid choice. Exiting.")
            return

    columns, rows = _load_csv(file_to_plot)
    if "time" not in columns:
        print("Invalid format: 'time' column missing.")
        return

    times = _col_to_array(rows, "time")
    vehicle_ids = _extract_vehicle_ids(columns)
    active = _active_vehicles(rows, columns, vehicle_ids)

    if not active:
        print("No active vehicle data found.")
        return

    # Determine host vehicle from filename
    host_match = re.search(r"V(\d+)\.csv$", os.path.basename(file_to_plot))
    host_id = int(host_match.group(1)) if host_match else -1

    # Determine list of candidate focus vehicles (exclude host if possible)
    neighbors = [v for v in active if v != host_id]
    focus_candidates = neighbors or active[:]

    print(f"Host vehicle: V{host_id}")
    print(f"Active vehicles: {active}")
    print(f"Candidate focus vehicles: {focus_candidates}")
    print(f"Total samples: {len(rows)}\n")

    if args.playback:
        if args.focus is not None and args.focus in focus_candidates:
            playback_focus = args.focus
        elif args.focus is not None and args.focus in active:
            playback_focus = args.focus
        else:
            playback_focus = focus_candidates[0]

        print(
            f"Starting realtime playback with focus vehicle V{playback_focus} "
            f"at {args.speed:g}x speed."
        )
        _run_playback_dashboard(
            file_to_plot=file_to_plot,
            times=times,
            rows=rows,
            columns=columns,
            active=active,
            focus=playback_focus,
            host_id=host_id,
            speed=args.speed,
            window_s=args.window,
            interval_ms=args.playback_interval,
            start_time=args.start_time,
            loop=not args.no_loop,
            max_points=args.max_points,
        )
        plt.show()
        return

    # Print analytic summary
    _print_static_metrics(rows, active)

    # Choose focus vehicles according to command-line flags or interactive input
    if args.all:
        focuses = focus_candidates
    elif args.focus is not None:
        if args.focus in focus_candidates:
            focuses = [args.focus]
        else:
            print(f"Requested focus V{args.focus} not in candidate list; using {focus_candidates[0]}")
            focuses = [focus_candidates[0]]
    else:
        # interactive prompt if no CLI preference provided
        focus_selection = input(
            "Enter a focus vehicle ID from the list above, or type 'all' to generate a separate set of figures for every candidate (default = first): "
        ).strip().lower()

        if focus_selection == "all":
            focuses = focus_candidates
        else:
            try:
                fid = int(focus_selection)
                focuses = [fid] if fid in focus_candidates else [focus_candidates[0]]
            except ValueError:
                focuses = [focus_candidates[0]]

    # Build the figures (multiple sets if necessary)
    for focus in focuses:
        print(f"Plotting figures with focus vehicle: V{focus} ...")
        _fig_trust(times, rows, active, focus, host_id)
        _fig_weights(times, rows, active, host_id)
        _fig_estimation(times, rows, active, host_id)
        _fig_impact_histograms(rows, active, focus, host_id)
        _fig_v2v_details(times, rows, active, focus, host_id)

    if not args.skip_relative:
        relative_file = args.relative_file or _find_relative_uio_log(directory, host_id)
        if relative_file and os.path.isfile(relative_file):
            print(f"Plotting relative UIO diagnostics: {os.path.basename(relative_file)}")
            _fig_relative_uio(relative_file, host_id)
        elif args.relative_file:
            print(f"Specified relative UIO file does not exist: {args.relative_file}")

    plt.show()


if __name__ == "__main__":
    main()
