vehicle_model_parameters:
  mass: 1.0
  inertia: 0.1
  wheelbase: 0.3
  air_resistance: 0.1
  friction_coefficient: 0.1

observer:
  common:
    initial_pose:
      x: 0.0
      y: 0.0
      theta: 0.0
  luenberger:

  ekf:

  high_gain:

path_planner:
  common:
    lookahead_distance: 0.5
    max_steering_angle: 0.48
    max_throttle: 0.10
    min_throttle: -0.10
    max_speed: 1.0
    min_speed: -1.0
  
controller:
  common:
    max_steering_angle: 0.48
    max_throttle: 0.10
    min_throttle: -0.10
    max_speed: 1.0
    min_speed: -1.0
  
  controller_simple:
    lookahead_distance: 0.5
    kp_velocity: 0.2
    ki_velocity: 0.0
    kd_velocity: 0.0
    feedforward_gain: 0.0
    steering_gain: 1.0
    max_throttle: 0.10
    min_throttle: -0.10
    max_steering: 0.48
    integral_limit: 1.0
