"null":
  implementation: "null"

simple_qcar:
  implementation: simple
  lookahead_distance: 0.5
  kp_velocity: 0.2
  ki_velocity: 0.0
  kd_velocity: 0.0
  feedforward_gain: 0.0
  steering_gain: 1.0
  max_throttle: 0.10
  min_throttle: -0.10
  max_steering: 0.48
  integral_limit: 1.0

simple_carla:
  implementation: simple
  kp_velocity: 0.35
  ki_velocity: 0.02
  kd_velocity: 0.0
  feedforward_gain: 0.0
  steering_gain: 0.75
  max_throttle: 0.15
  min_throttle: -0.15
  max_steering: 0.48
  integral_limit: 1.0
