simulation_profile: "null"

fleet:
  profile: default
  formation_id: virtual_two_vehicle_fleet_control
  members:
    - {vehicle_id: 1, role: leader, member_order: 0}
    - {vehicle_id: 2, role: follower, member_order: 1}

vehicles:
  - vehicle_id: 1
    vehicle_config_file: config_vehicle_virtual.yaml
    controller_profile: simple_qcar
    initial_pose: [0.0, 0.0, 0.0]
    v2v_profile: udp_default
    v2v: {bind_ip: "127.0.0.1", peers: [{vehicle_id: 2, ip: "127.0.0.1"}]}
    mission:
      path: [[0.0, 0.0], [2.0, 0.2], [4.0, 0.0]]
      target_velocity: 0.3
  - vehicle_id: 2
    vehicle_config_file: config_vehicle_virtual.yaml
    controller_profile: fleet_2d_virtual
    initial_pose: [-0.8, 0.0, 0.0]
    v2v_profile: udp_default
    v2v: {bind_ip: "127.0.0.1", peers: [{vehicle_id: 1, ip: "127.0.0.1"}]}
    mission:
      path: [[-0.8, 0.0], [2.0, 0.0], [4.0, 0.0]]
      target_velocity: 0.3
