import numpy as np
from hal.products.mats import SDCSRoadMap
import matplotlib.image as mpimg
import os
# Node 0: Pose = [0.0, 0.13024, -1.5707963267948966]
# Node 1: Pose = [0.26861999999999997, 0.0814, 1.5707963267948966]
# Node 2: Pose = [1.12739, -1.084655, 0.0]
# Node 3: Pose = [1.12739, -0.814, 3.141592653589793]
# Node 4: Pose = [2.25478, 0.0814, 1.5707963267948966]
# Node 5: Pose = [1.984125, 0.0814, -1.5707963267948966]
# Node 6: Pose = [1.01343, 1.100935, 3.141592653589793]
# Node 7: Pose = [1.235245, 0.83028, 0.0]
# Node 8: Pose = [-0.74888, 1.100935, 3.141592653589793]
# Node 9: Pose = [-0.74888, 0.83028, 0.0]
# Node 10: Pose = [-1.28205, -0.45991, -0.7330382858376184]
# Node 11: Pose = [0.0, 2.163205, -1.5707963267948966]
# Node 12: Pose = [0.0, 1.849815, -1.5707963267948966]
# Node 13: Pose = [0.26861999999999997, 1.849815, 1.5707963267948966]
# Node 14: Pose = [2.25478, 2.96703, 1.5707963267948966]
# Node 15: Pose = [1.984125, 1.849815, -1.5707963267948966]
# Node 16: Pose = [0.9076099999999999, 3.709805, -1.4067353771074296]
# Node 17: Pose = [1.4660140000000002, 3.1511975, -0.16406094968746698]
# Node 18: Pose = [0.62271, 3.066745, -2.4085543677521746]
# Node 19: Pose = [0.791615, 2.859175, 0.7330382858376184]
# Node 20: Pose = [0.0, 4.49735, 3.141592653589793]
# Node 21: Pose = [0.0, 4.226694999999999, 0.0]
# Node 22: Pose = [-1.984125, 2.96703, -1.5707963267948966]
# Node 23: Pose = [-1.7155049999999998, 2.96703, 1.5707963267948966]


def main():
    # Configuration parameters for example script.
    useSmallMap = False
    leftHandTraffic = False
    nodeSequence = [10, 11, 10]

    # Create a SDCSRoadMap instance with desired configuration.
    roadmap = SDCSRoadMap(leftHandTraffic=leftHandTraffic, useSmallMap=useSmallMap)

    # Generate the shortest path passing through the given sequence of nodes.
    # - nodeSequence can be a list or tuple of node indicies.
    # - The generated path takes the form of a 2xn numpy array
    path = roadmap.generate_path(nodeSequence=nodeSequence)

    # Print out the location of each node
    for i, node in enumerate(roadmap.nodes):
        print(
            "Node "
            + str(i)
            + ": Pose = ["
            + str(node.pose[0, 0])
            + ", "
            + str(node.pose[1, 0])
            + ", "
            + str(node.pose[2, 0])
            + "]"
        )

    # Display the roadmap with nodes, edges, and labels using matplotlib.
    plt, ax = roadmap.display()

    # Add the SDCS mats as a background image to the plot generated by display.
    if useSmallMap:
        imgFile = "./SDCS_SmallMapLayout.png"
        yOrigin = 299.5
    else:
        imgFile = "./SDCS_MapLayout.png"
        yOrigin = 1008.5

    imgPath = os.path.normpath(os.path.join(os.path.dirname(__file__), imgFile))
    img = mpimg.imread(imgPath)
    img = np.flipud(img)
    scale = 0.00476556
    x_translation, y_translation = -483.5 * scale, (yOrigin - img.shape[0]) * scale
    img_extent = (
        x_translation,
        img.shape[1] * scale + x_translation,
        y_translation,
        img.shape[0] * scale + y_translation,
    )
    ax.imshow(img, extent=img_extent, origin="lower", zorder=0)

    # Plot the generated path, if one exists
    if path is None:
        print("failed to find path")
    else:
        ax.plot(path[0, :], path[1, :], "red", linestyle="-", linewidth=2)

    plt.show()


if __name__ == "__main__":
    main()
