# Fleet Configuration File
# Easy to modify configuration for QCar fleet simulation
# Simply change values below and run your simulation

# =============================================================================
# ACTIVE PRESET - EASY SWITCHING!
# =============================================================================
# Uncomment ONE of these to quickly switch between configurations:
# active_preset: "openroad_cacc"    # OpenRoad configuration (outdoor, larger scale)
active_preset: "studio_cacc"      # Studio configuration (indoor, smaller scale)
# Leave BOTH commented (or remove active_preset) to use manual configuration below

# When active_preset is set, it will automatically configure:
# - road_type, controller_type, node_sequence
# - max_velocity, lookahead_distance
# - All controller parameters (alpha, beta, v0, s0, ri, hi, etc.)
# You can still override individual values in sections below!

# =============================================================================
# SIMULATION SETTINGS
# =============================================================================
simulation:
  time: 60                        # Simulation duration in seconds (0 = unlimited)
  road_type: "OpenRoad"             # "OpenRoad" or "Studio" (overridden by preset if set)
  controller_type: "CACC"         # "CACC" or "IDM" or "LOOKAHEAD" (only use for following controllers)

# =============================================================================
# FLEET SETTINGS
# =============================================================================
fleet:
  num_vehicles: 2                 # Number of vehicles in fleet (2-5) - Testing chain following
  leader_index: 0                 # Which vehicle is the leader (0-based)
  distance_between_cars: 0.2      # Distance between vehicles (meters)

# =============================================================================
# VEHICLE CONTROL PARAMETERS
# =============================================================================
control:
  max_velocity: 2.0               # Maximum vehicle velocity (m/s)
  max_steering: 0.6               # Maximum steering angle (radians)
  lookahead_distance: 7.0         # Path following lookahead distance (meters)
  enable_steering_control: false  # Enable steering control (false for OpenRoad straight path)
  
  # Update rates (Hz)
  general_update_rate: 50         # Main control loop rate
  controller_rate: 100              # Controller update rate
  observer_rate: 100               # Observer update rate
  gps_update_rate: 5               # GPS update rate

# =============================================================================
# PATH SETTINGS
# =============================================================================
path:
  rebuild_path: true              # Whether to rebuild the path
  # node_sequence: [10, 4, 20, 13, 10]  # Path nodes for Studio
  node_sequence: [0, 1]         # Path nodes for OpenRoad (uncomment if needed)

# =============================================================================
# CONTROLLER PARAMETERS
# =============================================================================
# These parameters control the vehicle following behavior
controller_params:
  # Car-following parameters
  alpha: 1.0                      # Acceleration sensitivity
  beta: 1.5                       # Deceleration sensitivity
  v0: 1.0                         # Desired velocity (m/s)
  delta: 4                        # Acceleration exponent
  T: 0.4                          # Time headway (seconds)
  s0: 7                           # Minimum spacing (meters)
  ri: 7                           # CACC spacing parameter (meters)
  hi: 0.5                         # Time headway for CACC (seconds)
  
  # Control gains (2x2 matrix as [K11, K12, K21, K22])
  K_gains: [1.0, 0.0, 0.0, 1.0]  # Control gain matrix

# =============================================================================
# OBSERVER SETTINGS
# =============================================================================
observer:
  enable_distributed: true        # Enable distributed state estimation
  local_observer_type: "kalman"   # "kalman", "luenberger", or "direct"
  distributed_observer_type: "consensus"  # Type of distributed observer
  consensus_gain: 0.1             # Consensus gain for distributed observer

# =============================================================================
# COMMUNICATION SETTINGS
# =============================================================================
communication:
  use_communication: true         # Enable inter-vehicle communication
  communication_delay: 0.01       # Communication delay (seconds)
  gps_server_ip: "127.0.0.1"      # GPS server IP address
  gps_server_port: 8001           # GPS server port

# =============================================================================
# PHYSICAL QCAR SETTINGS (for real hardware)
# =============================================================================
physical_qcar:
  use_physical_qcar: true        # Use physical QCar hardware (leader only)
  use_control_observer_mode: true # Use control observer mode with physical QCar
  calibrate: true                # Calibrate GPS on startup

# =============================================================================
# LOGGING SETTINGS
# =============================================================================
logging:
  enable_performance_monitoring: false  # Enable performance monitoring
  log_level: "INFO"               # Logging level: DEBUG, INFO, WARNING, ERROR

# =============================================================================
# DATA LOGGING SETTINGS
# =============================================================================
data_logging:
  create_new_run: true            # If true, creates new timestamped directory each run
                                  # If false, reuses "current_run" directory (overwrites data)
  custom_run_name: current_run           # Custom name for run directory (e.g., "experiment_1")
                                  # Set to null to use timestamp or "current_run"

# =============================================================================
# SENSOR SETTINGS
# =============================================================================
enable_cam_lidar_fusion: false
enable_visualization_camera: false
enable_visualization_lidar: false

# =============================================================================
# PRESET CONFIGURATIONS
# =============================================================================
# Uncomment one of these sections to quickly switch between common configurations

# # OpenRoad CACC Configuration
# preset_openroad_cacc:
#   simulation:
#     road_type: "OpenRoad"
#     controller_type: "CACC"
#   control:
#     max_velocity: 2.0
#     lookahead_distance: 7.0
#   path:
#     node_sequence: [0, 1]
#   controller_params:
#     alpha: 1.0
#     beta: 1.5
#     v0: 1.0
#     delta: 4
#     T: 0.4
#     s0: 7
#     ri: 7
#     hi: 0.5
#     K_gains: [1.0, 0.0, 0.0, 1.0]

# # Studio CACC Configuration (Current Active)
# preset_studio_cacc:
#   simulation:
#     road_type: "Studio"
#     controller_type: "CACC"
#   control:
#     max_velocity: 0.5
#     lookahead_distance: 0.5
#   path:
#     node_sequence: [10, 4, 20, 13, 10]
#   controller_params:
#     alpha: 1.2
#     beta: 2.0
#     v0: 0.5
#     delta: 3
#     T: 0.3
#     s0: 1
#     ri: 1
#     hi: 0.3
#     K_gains: [1.1, 0.0, 0.0, 1.1]
